### ISSUE TITLE
Port 9001 in use on Windows 10 (ZMQ: GUI training)

### ISSUE THREAD

**Issue by KennyTC** [talmolab/sleap#1032]
# Bug description

## Expected behaviour

able to run training single-animal model

## Actual behaviour

due to the error, unable to run training single-animal model

## Your personal set up

- OS: Windows 10

- Version(s): SLEAP v1.2.8, python 3.8

</details>
## Screenshots

```
(sleap-vuWYjmAg) C:\Users\Projects\09_animalpose\sleap>sleap-label
Saving config: C:\Users\.sleap/1.2.8/preferences.yaml
Restoring GUI state...

Software versions:
SLEAP: 1.2.8
TensorFlow: 2.8.3
Numpy: 1.22.4
Python: 3.8.5
OS: Windows-10-10.0.18362-SP0

Happy SLEAPing! :)
Traceback (most recent call last):
  File "C:\Users\.virtualenvs\sleap-vuWYjmAg\lib\site-packages\sleap\gui\learning\dialog.py", line 593, in run
    new_counts = runners.run_learning_pipeline(
  File "C:\Users\.virtualenvs\sleap-vuWYjmAg\lib\site-packages\sleap\gui\learning\runners.py", line 545, in run_learning_pipeline
    trained_job_paths = run_gui_training(
  File "C:\Users\virtualenvs\sleap-vuWYjmAg\lib\site-packages\sleap\gui\learning\runners.py", line 597, in run_gui_training
    win = LossViewer()
  File "C:\Users\.virtualenvs\sleap-vuWYjmAg\lib\site-packages\sleap\gui\widgets\monitor.py", line 44, in __init__
    self.setup_zmq(zmq_context)
  File "C:\Users\.virtualenvs\sleap-vuWYjmAg\lib\site-packages\sleap\gui\widgets\monitor.py", line 308, in setup_zmq
    self.sub.bind("tcp://127.0.0.1:9001")
  File "C:\Users\.virtualenvs\sleap-vuWYjmAg\lib\site-packages\zmq\sugar\socket.py", line 232, in bind
    super().bind(addr)
  File "zmq\backend\cython\socket.pyx", line 568, in zmq.backend.cython.socket.Socket.bind
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
```

## How to reproduce

1. Go to 'File > Import Project > Select .slp file'
2. Click on 'Predcit > Run Training > Select single animal in Training/Inference Pipeline Type'
3. Click 'Run'

**Comment by KennyTC** [comment]
It seems restart SLEAP, or  restart the computer, can resolve  the problem.

**Comment by roomrys** [comment]
Hi @KennyTC,

Are you already running training on another dataset on the same computer? We use a single address to relay information and thus can only handle one training at a time.

Let me know if this helps - otherwise, there may be something else going on.

Thanks,
Liezl

**Comment by KennyTC** [comment]
I am running only 1 training task. I have shutdown the GUI and  run again but the error was still there. Maybe restart the computer may work but it is tough to do it each time.

**Comment by roomrys** [comment]
From the lines
```
  File "C:\Users\.virtualenvs\sleap-vuWYjmAg\lib\site-packages\sleap\gui\widgets\monitor.py", line 308, in setup_zmq
    self.sub.bind("tcp://127.0.0.1:9001")
  File "C:\Users\.virtualenvs\sleap-vuWYjmAg\lib\site-packages\zmq\sugar\socket.py", line 232, in bind
    super().bind(addr)
  File "zmq\backend\cython\socket.pyx", line 568, in zmq.backend.cython.socket.Socket.bind
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
```

it seems that port 9001 is already in use by some other process. From [this post](https://github.com/eclipse/mosquitto/issues/1580), it appears Intel has started using that port for their graphics card. 

Some possible fixes are to:
1. use another port for SLEAP training
2. find available port from list of ports to use for SLEAP training
3. allow the user to specify a port to use

Some possible workarounds are to: 
1. [find ](https://dzone.com/articles/how-to-check-which-process-is-using-port-8080-or-a)and disable whichever process is running on port 9001 
2. run training through the command line using the [`sleap-train`](https://sleap.ai/guides/cli.html?highlight=sleap%20train#sleap-train) command.

**Comment by RoboDoig** [comment]
Sorry to add to a closed issue but I didn't see anything current in the open issues.

Just wanted to say in case it helps anyone else, I ran into this problem today myself and realised that the process blocking port 9001 was the python interface for running ipynb notebooks in VSCode. I imagine this might be a common occurence for other SLEAP users!

In powershell, culprit process for blocking the port can be found with:
Get-Process -Id (Get-NetTCPConnection -LocalPort 9001).OwningProcess
