### ISSUE TITLE
Training: config option to `split_by_inds` is broken

### ISSUE THREAD

**Issue by roomrys** [talmolab/sleap#1059]
# Bug description
If I set the option in the training_config.json `"split_by_inds": true`, training fails.

## Expected behaviour
Training does not fail and uses the indices provided in `training_inds`, `validation_inds`, and `test_inds` respectively for training, validation, and testing.

## Your personal set up

- OS:

- Version(s):

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [M1 Macs](https://sleap.ai/installation.html#m1-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
(sleap) λ C:/Users/Liezl/miniconda3/envs/sleap/python.exe c:/Users/Liezl/Projects/sleap-estimates-animal-poses/pull-requests/sleap/sleap/nn/training.py
INFO:__main__:Versions:
SLEAP: 1.2.9
TensorFlow: 2.8.3
Numpy: 1.21.5
Python: 3.7.15
OS: Windows-10-10.0.19041-SP0
INFO:__main__:Training labels file: None
INFO:__main__:Training profile: C:\Users\Liezl\Projects\sleap-estimates-animal-poses\datasets\drosophila-melanogaster-courtship\models\221118_200659.centroid.n=149\training_config.json       
INFO:__main__:
INFO:__main__:Arguments:
INFO:__main__:{
    "training_job_path": "C:\\Users\\Liezl\\Projects\\sleap-estimates-animal-poses\\datasets\\drosophila-melanogaster-courtship\\models\\221118_200659.centroid.n=149\\training_config.json",  
    "labels_path": null,
    "video_paths": [
        ""
    ],
    "val_labels": null,
    "test_labels": null,
    "tensorboard": false,
    "save_viz": false,
    "zmq": false,
    "run_name": "",
    "prefix": "",
    "suffix": "",
    "cpu": false,
    "first_gpu": false,
    "last_gpu": false,
    "gpu": "auto"
}
INFO:__main__:
INFO:__main__:Training job:
INFO:__main__:{
    "data": {
        "labels": {
            "training_labels": "D:\\Users\\Liezl\\ProjectsData\\sleap-estimates-animal-poses\\datasets\\drosophila-melanogaster-courtship\\courtship_labels.slp",
            "validation_labels": "C:\\Users\\Liezl\\Projects\\sleap-estimates-animal-poses\\datasets\\drosophila-melanogaster-courtship\\validation_labels.slp",
            "validation_fraction": 0.1,
            "test_labels": null,
            "split_by_inds": true,
            "training_inds": [
                53,
                132,
                78,
                123,
                106,
                59,
                10,
                139,
                125,
                36,
                45,
                42,
                133,
                130,
                116,
                148,
                135,
                47,
                44,
                97,
                119,
                2,
                3,
                4,
                73,
                126,
                86,
                72,
                41,
                7,
                67,
                124,
                95,
                80,
                64,
                23,
                43,
                50,
                66,
                38,
                5,
                52,
                92,
                1,
                28,
                56,
                30,
                128,
                121,
                35,
                91,
                37,
                98,
                40,
                68,
                111,
                112,
                93,
                9,
                13,
                90,
                94,
                46,
                25,
                100,
                31,
                79,
                129,
                14,
                141,
                102,
                99,
                145,
                22,
                6,
                12,
                65,
                63,
                16,
                15,
                32,
                57,
                81,
                18,
                143,
                0,
                54,
                17,
                114,
                77,
                118,
                144,
                58,
                82,
                24,
                140,
                138,
                33,
                136,
                84,
                104,
                49,
                69,
                110,
                108,
                26,
                122,
                117,
                21,
                34,
                60,
                71,
                134,
                48,
                87,
                83,
                146,
                147,
                51,
                103,
                19,
                131,
                115,
                85,
                70,
                76,
                61,
                75,
                109,
                29,
                27,
                113,
                137,
                107
            ],
            "validation_inds": [
                149
            ],
            "test_inds": null,
            "search_path_hints": [
                "",
                "",
                "",
                "",
                "",
                ""
            ],
            "skeletons": [
                {
                    "directed": true,
                    "graph": {
                        "name": "Skeleton-0",
                        "num_edges_inserted": 46
                    },
                    "links": [
                        {
                            "edge_insert_idx": 44,
                            "key": 0,
                            "source": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "head",
                                        1.0
                                    ]
                                }
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "eyeL",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/reduce": [
                                    {
                                        "py/type": "sleap.skeleton.EdgeType"
                                    },
                                    {
                                        "py/tuple": [
                                            1
                                        ]
                                    }
                                ]
                            }
                        },
                        {
                            "edge_insert_idx": 45,
                            "key": 0,
                            "source": {
                                "py/id": 1
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "eyeR",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 34,
                            "key": 0,
                            "source": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "thorax",
                                        1.0
                                    ]
                                }
                            },
                            "target": {
                                "py/id": 1
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 35,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "abdomen",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 36,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "wingL",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 37,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "wingR",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 38,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "forelegL4",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 39,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "forelegR4",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 40,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "midlegL4",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 41,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "midlegR4",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 42,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "hindlegL4",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        },
                        {
                            "edge_insert_idx": 43,
                            "key": 0,
                            "source": {
                                "py/id": 5
                            },
                            "target": {
                                "py/object": "sleap.skeleton.Node",
                                "py/state": {
                                    "py/tuple": [
                                        "hindlegR4",
                                        1.0
                                    ]
                                }
                            },
                            "type": {
                                "py/id": 3
                            }
                        }
                    ],
                    "multigraph": true,
                    "nodes": [
                        {
                            "id": {
                                "py/id": 1
                            }
                        },
                        {
                            "id": {
                                "py/id": 5
                            }
                        },
                        {
                            "id": {
                                "py/id": 6
                            }
                        },
                        {
                            "id": {
                                "py/id": 7
                            }
                        },
                        {
                            "id": {
                                "py/id": 8
                            }
                        },
                        {
                            "id": {
                                "py/id": 9
                            }
                        },
                        {
                            "id": {
                                "py/id": 10
                            }
                        },
                        {
                            "id": {
                                "py/id": 11
                            }
                        },
                        {
                            "id": {
                                "py/id": 12
                            }
                        },
                        {
                            "id": {
                                "py/id": 13
                            }
                        },
                        {
                            "id": {
                                "py/id": 14
                            }
                        },
                        {
                            "id": {
                                "py/id": 2
                            }
                        },
                        {
                            "id": {
                                "py/id": 4
                            }
                        }
                    ]
                }
            ]
        },
        "preprocessing": {
            "ensure_rgb": false,
            "ensure_grayscale": false,
            "imagenet_mode": null,
            "input_scaling": 0.5,
            "pad_to_stride": 16,
            "resize_and_pad_to_target": true,
            "target_height": 1024,
            "target_width": 1024
        },
        "instance_cropping": {
            "center_on_part": "thorax",
            "crop_size": null,
            "crop_size_detection_padding": 16
        }
    },
    "model": {
        "backbone": {
            "leap": null,
            "unet": {
                "stem_stride": null,
                "max_stride": 16,
                "output_stride": 2,
                "filters": 16,
                "filters_rate": 2.0,
                "middle_block": true,
                "up_interpolate": true,
                "stacks": 1
            },
            "hourglass": null,
            "resnet": null,
            "pretrained_encoder": null
        },
        "heads": {
            "single_instance": null,
            "centroid": {
                "anchor_part": "thorax",
                "sigma": 2.5,
                "output_stride": 2,
                "loss_weight": 1.0,
                "offset_refinement": false
            },
            "centered_instance": null,
            "multi_instance": null,
            "multi_class_bottomup": null,
            "multi_class_topdown": null
        }
    },
    "optimization": {
        "preload_data": true,
        "augmentation_config": {
            "rotate": true,
            "rotation_min_angle": -15.0,
            "rotation_max_angle": 15.0,
            "translate": false,
            "translate_min": -5,
            "translate_max": 5,
            "scale": false,
            "scale_min": 0.9,
            "scale_max": 1.1,
            "uniform_noise": false,
            "uniform_noise_min_val": 0.0,
            "uniform_noise_max_val": 10.0,
            "gaussian_noise": false,
            "gaussian_noise_mean": 5.0,
            "gaussian_noise_stddev": 1.0,
            "contrast": false,
            "contrast_min_gamma": 0.5,
            "contrast_max_gamma": 2.0,
            "brightness": false,
            "brightness_min_val": 0.0,
            "brightness_max_val": 10.0,
            "random_crop": false,
            "random_crop_height": 256,
            "random_crop_width": 256,
            "random_flip": false,
            "flip_horizontal": true
        },
        "online_shuffling": true,
        "shuffle_buffer_size": 128,
        "prefetch": true,
        "batch_size": 4,
        "batches_per_epoch": 200,
        "min_batches_per_epoch": 200,
        "val_batches_per_epoch": 10,
        "min_val_batches_per_epoch": 10,
        "epochs": 200,
        "optimizer": "adam",
        "initial_learning_rate": 0.0001,
        "learning_rate_schedule": {
            "reduce_on_plateau": true,
            "reduction_factor": 0.5,
            "plateau_min_delta": 1e-06,
            "plateau_patience": 5,
            "plateau_cooldown": 3,
            "min_learning_rate": 1e-08
        },
        "hard_keypoint_mining": {
            "online_mining": false,
            "hard_to_easy_ratio": 2.0,
            "min_hard_keypoints": 2,
            "max_hard_keypoints": null,
            "loss_scale": 5.0
        },
        "early_stopping": {
            "stop_training_on_plateau": true,
            "plateau_min_delta": 1e-08,
            "plateau_patience": 20
        }
    },
    "outputs": {
        "save_outputs": true,
        "run_name": "221118_200659.centroid.n=149",
        "run_name_prefix": "",
        "run_name_suffix": "",
        "runs_folder": "D:\\Users\\Liezl\\ProjectsData\\sleap-estimates-animal-poses\\datasets\\drosophila-melanogaster-courtship\\models",
        "tags": [
            ""
        ],
        "save_visualizations": true,
        "delete_viz_images": false,
        "zip_outputs": false,
        "log_to_csv": true,
        "checkpointing": {
            "initial_model": false,
            "best_model": true,
            "every_epoch": false,
            "latest_model": false,
            "final_model": false
        },
        "tensorboard": {
            "write_logs": false,
            "loss_frequency": "epoch",
            "architecture_graph": false,
            "profile_graph": false,
            "visualizations": true
        },
        "zmq": {
            "subscribe_to_controller": true,
            "controller_address": "tcp://127.0.0.1:9000",
            "controller_polling_timeout": 10,
            "publish_updates": true,
            "publish_address": "tcp://127.0.0.1:9001"
        }
    },
    "name": "",
    "description": "",
    "sleap_version": "1.2.9",
    "filename": "C:\\Users\\Liezl\\Projects\\sleap-estimates-animal-poses\\datasets\\drosophila-melanogaster-courtship\\models\\221118_200659.centroid.n=149\\training_config.json"
}
INFO:__main__:
INFO:__main__:Auto-selected GPU 0 with 12024 MiB of free memory.
INFO:__main__:Using GPU 0 for acceleration.
INFO:__main__:Disabled GPU memory pre-allocation.
INFO:__main__:System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
INFO:__main__:
INFO:__main__:Initializing trainer...
INFO:__main__:Loading training labels from: D:\Users\Liezl\ProjectsData\sleap-estimates-animal-poses\datasets\drosophila-melanogaster-courtship\courtship_labels.slp
INFO:__main__:Creating validation split from explicit indices (n = 1).
INFO:__main__:Creating training split from explicit indices (n = 134).
Traceback (most recent call last):
  File "c:/Users/Liezl/Projects/sleap-estimates-animal-poses/pull-requests/sleap/sleap/nn/training.py", line 1990, in <module>
    main([training_job_path])  # "--val_labels", validation_labels])
  File "c:/Users/Liezl/Projects/sleap-estimates-animal-poses/pull-requests/sleap/sleap/nn/training.py", line 1979, in main
    video_search_paths=args.video_paths,
  File "c:/Users/Liezl/Projects/sleap-estimates-animal-poses/pull-requests/sleap/sleap/nn/training.py", line 675, in from_config
    with_track_only=is_id_model,
  File "c:/Users/Liezl/Projects/sleap-estimates-animal-poses/pull-requests/sleap/sleap/nn/training.py", line 151, in from_config
    with_track_only=with_track_only,
  File "c:/Users/Liezl/Projects/sleap-estimates-animal-poses/pull-requests/sleap/sleap/nn/training.py", line 243, in from_labels
    training, with_track_only=with_track_only
  File "c:\users\liezl\projects\sleap-estimates-animal-poses\pull-requests\sleap\sleap\nn\data\providers.py", line 55, in from_user_instances
    labels.remove_empty_instances(keep_empty_frames=False)
AttributeError: 'list' object has no attribute 'remove_empty_instances'
```

</details>

## How to reproduce

1. Edit training_config.json s.t. `"split_by_inds": true` and there is a list of values for `"training_inds"` and `"validation_inds"`.
2. `sleap-train <path to training_config.json>`
3. See error

**Comment by roomrys** [comment]
## Problem
The `DataReaders.from_labels` method reads in the variables `validation`, `test`, and `training` as `List[LabeledFrames]`, 
https://github.com/talmolab/sleap/blob/5093f6992e6214c0d528b7240331b99d0a89a62f/sleap/nn/training.py#L172-L197
but later on expects these variables to be `Labels`
https://github.com/talmolab/sleap/blob/5093f6992e6214c0d528b7240331b99d0a89a62f/sleap/nn/training.py#L241-L249

## Solution
```python
validation = sleap.Labels(training[labels_config.validation_inds])
```

```python
test = sleap.Labels(training[labels_config.test_inds])
```

```python
training = sleap.Labels(training[labels_config.training_inds])
```
