### ISSUE TITLE
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by catubc** [talmolab/sleap#1077]
Hello

So after upgrading sleap, the GUI won't load. Not sure if this is a bug, or some issue with my linux laptop .  I also checked on a fresh conda environment with only sleap installed and I get the same crash.

Ubuntu 22.04
no GPU
python 3.10.6

Thanks so much for the help.

```

gerbils) cat@cat-930QDB:~$ pip install --upgrade sleap
Requirement already satisfied: sleap in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (1.2.9)
Requirement already satisfied: imgstore==0.2.9 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (0.2.9)
Requirement already satisfied: PySide2<=5.14.1,>=5.13.2 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (5.13.2)
Requirement already satisfied: attrs<=21.4.0,>=21.2.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (21.4.0)
Requirement already satisfied: pykalman==0.9.5 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (0.9.5)
Requirement already satisfied: h5py<=3.7.0,>=3.1.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (3.7.0)
Requirement already satisfied: scikit-image in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (0.19.3)
Requirement already satisfied: numpy<1.23.0,>=1.19.5 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.22.4)
Requirement already satisfied: qimage2ndarray>=1.9.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.9.0)
Requirement already satisfied: jsmin in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (3.0.1)
Requirement already satisfied: qtpy>=2.0.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (2.2.1)
Requirement already satisfied: scipy<=1.9.0,>=1.4.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.9.0)
Requirement already satisfied: tensorflow<2.9.0,>=2.6.3 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (2.8.3)
Requirement already satisfied: certifi<=2021.10.8,>=2017.4.17 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (2021.10.8)
Requirement already satisfied: networkx in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (2.8.7)
Requirement already satisfied: seaborn in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (0.12.1)
Requirement already satisfied: imageio<=2.15.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (2.15.0)
Requirement already satisfied: imgaug==0.4.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (0.4.0)
Requirement already satisfied: jsonpickle==1.2 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.2)
Requirement already satisfied: opencv-python<=4.6.0,>=4.2.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (4.5.5.64)
Requirement already satisfied: pynwb in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (2.1.0)
Requirement already satisfied: psutil in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (5.9.3)
Requirement already satisfied: scikit-video in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.1.11)
Requirement already satisfied: pyzmq in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (24.0.1)
Requirement already satisfied: segmentation-models==1.0.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.0.1)
Requirement already satisfied: python-rapidjson in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.9)
Requirement already satisfied: scikit-learn==1.0.* in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.0.2)
Requirement already satisfied: pandas in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.5.0)
Requirement already satisfied: cattrs==1.1.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (1.1.1)
Requirement already satisfied: rich==10.16.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (10.16.1)
Requirement already satisfied: pillow<=8.4.0,>=8.3.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (8.4.0)
Requirement already satisfied: pyyaml in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (6.0)
Requirement already satisfied: ndx-pose in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from sleap) (0.1.1)
Requirement already satisfied: six in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from imgaug==0.4.0->sleap) (1.16.0)
Requirement already satisfied: matplotlib in ./.local/lib/python3.10/site-packages (from imgaug==0.4.0->sleap) (3.6.2)
Requirement already satisfied: Shapely in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from imgaug==0.4.0->sleap) (1.8.5.post1)
Requirement already satisfied: pytz in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from imgstore==0.2.9->sleap) (2022.4)
Requirement already satisfied: tzlocal in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from imgstore==0.2.9->sleap) (4.2)
Requirement already satisfied: python-dateutil in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from imgstore==0.2.9->sleap) (2.8.2)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from rich==10.16.1->sleap) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from rich==10.16.1->sleap) (2.13.0)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from rich==10.16.1->sleap) (0.4.5)
Requirement already satisfied: joblib>=0.11 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from scikit-learn==1.0.*->sleap) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from scikit-learn==1.0.*->sleap) (3.1.0)
Requirement already satisfied: image-classifiers==1.0.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from segmentation-models==1.0.1->sleap) (1.0.0)
Requirement already satisfied: keras-applications<=1.0.8,>=1.0.7 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from segmentation-models==1.0.1->sleap) (1.0.8)
Requirement already satisfied: efficientnet==1.0.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from segmentation-models==1.0.1->sleap) (1.0.0)
Requirement already satisfied: shiboken2==5.13.2 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from PySide2<=5.14.1,>=5.13.2->sleap) (5.13.2)
Requirement already satisfied: packaging in ./.local/lib/python3.10/site-packages (from qtpy>=2.0.1->sleap) (21.3)
Requirement already satisfied: tifffile>=2019.7.26 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from scikit-image->sleap) (2022.10.10)
Requirement already satisfied: PyWavelets>=1.1.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from scikit-image->sleap) (1.4.1)
Requirement already satisfied: tensorflow-estimator<2.9,>=2.8 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (2.8.0)
Requirement already satisfied: astunparse>=1.6.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (1.6.3)
Requirement already satisfied: flatbuffers>=1.12 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (22.9.24)
Requirement already satisfied: absl-py>=0.4.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (1.3.0)
Requirement already satisfied: wrapt>=1.11.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (1.14.1)
Requirement already satisfied: termcolor>=1.1.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (2.0.1)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (3.19.6)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (0.27.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (1.50.0)
Requirement already satisfied: gast>=0.2.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (0.5.3)
Requirement already satisfied: keras-preprocessing>=1.1.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (1.1.2)
Requirement already satisfied: google-pasta>=0.1.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (0.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (4.4.0)
Requirement already satisfied: setuptools in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (65.5.0)
Requirement already satisfied: opt-einsum>=2.3.2 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (3.3.0)
Requirement already satisfied: keras<2.9,>=2.8.0rc0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (2.8.0)
Requirement already satisfied: tensorboard<2.9,>=2.8 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (2.8.0)
Requirement already satisfied: libclang>=9.0.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorflow<2.9.0,>=2.6.3->sleap) (14.0.6)
Requirement already satisfied: hdmf<4,>=2.5.6 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from ndx-pose->sleap) (3.4.6)
Requirement already satisfied: wheel<1.0,>=0.23.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow<2.9.0,>=2.6.3->sleap) (0.37.1)
Requirement already satisfied: ruamel.yaml<1,>=0.16 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from hdmf<4,>=2.5.6->ndx-pose->sleap) (0.17.21)
Requirement already satisfied: jsonschema<5,>=2.6.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from hdmf<4,>=2.5.6->ndx-pose->sleap) (4.16.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.10/site-packages (from matplotlib->imgaug==0.4.0->sleap) (1.4.4)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.10/site-packages (from matplotlib->imgaug==0.4.0->sleap) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.10/site-packages (from matplotlib->imgaug==0.4.0->sleap) (4.37.4)
Requirement already satisfied: pyparsing>=2.2.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from matplotlib->imgaug==0.4.0->sleap) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in ./.local/lib/python3.10/site-packages (from matplotlib->imgaug==0.4.0->sleap) (1.0.5)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (1.8.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (0.6.1)
Requirement already satisfied: requests<3,>=2.21.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (2.28.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (2.13.0)
Requirement already satisfied: markdown>=2.6.8 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (3.4.1)
Requirement already satisfied: werkzeug>=0.11.15 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (2.2.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (0.4.6)
Requirement already satisfied: pytz-deprecation-shim in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from tzlocal->imgstore==0.2.9->sleap) (0.1.0.post0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (1.3.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from jsonschema<5,>=2.6.0->hdmf<4,>=2.5.6->ndx-pose->sleap) (0.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (3.4)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from ruamel.yaml<1,>=0.16->hdmf<4,>=2.5.6->ndx-pose->sleap) (0.2.6)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from werkzeug>=0.11.15->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (2.1.1)
Requirement already satisfied: tzdata in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from pytz-deprecation-shim->tzlocal->imgstore==0.2.9->sleap) (2022.5)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in ./miniconda3/envs/gerbils/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow<2.9.0,>=2.6.3->sleap) (3.2.2)
(gerbils) cat@cat-930QDB:~$ sleap-label
2022-12-12 07:51:20.025593: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/cat/miniconda3/envs/gerbils/lib/python3.10/site-packages/cv2/../../lib64:
2022-12-12 07:51:20.025652: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Saving config: /home/cat/.sleap/1.2.9/preferences.yaml
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/cat/miniconda3/envs/gerbils/bin/sleap-label", line 8, in <module>
    sys.exit(main())
  File "/home/cat/miniconda3/envs/gerbils/lib/python3.10/site-packages/sleap/gui/app.py", line 1859, in main
    window = MainWindow(
  File "/home/cat/miniconda3/envs/gerbils/lib/python3.10/site-packages/sleap/gui/app.py", line 174, in __init__
    self._initialize_gui()
  File "/home/cat/miniconda3/envs/gerbils/lib/python3.10/site-packages/sleap/gui/app.py", line 294, in _initialize_gui
    self._create_video_player()
  File "/home/cat/miniconda3/envs/gerbils/lib/python3.10/site-packages/sleap/gui/app.py", line 309, in _create_video_player
    self.player = QtVideoPlayer(
  File "/home/cat/miniconda3/envs/gerbils/lib/python3.10/site-packages/sleap/gui/widgets/video.py", line 228, in __init__
    self.seekbar = VideoSlider()
  File "/home/cat/miniconda3/envs/gerbils/lib/python3.10/site-packages/sleap/gui/widgets/slider.py", line 171, in __init__
    self.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
(gerbils) cat@cat-930QDB:~$ ^C
(gerbils) cat@cat-930QDB:~$ 


```

**Comment by talmo** [comment]
I'm going to guess that this is because it's Python 3.10 since Qt might not compatible in that one. Try 3.7-3.9 and see if you get the same issue.

**Comment by catubc** [comment]
Confirmed, downgrading to python=3.9 resolved the issue.
Thanks!
