### ISSUE TITLE
Problems running inference on server-located video

### ISSUE THREAD

**Issue by anarac97** [talmolab/sleap#1116]
Hi,
I'm a new SLEAPer and I've been experiencing some difficulties. I'm trying to track a single-animal video and I'm failing in running inference after I train my models - don't know why and would appreciate some help. Thanks a lot in advance!

### **Bug description**

I'm following the tutorial on SLEAP documentation. After labeling 20 randomly distributed frames throughout the video, I chose a top-down model (as I've seen in previous GitHub issues - and have experienced it myself - that single-animal models can give errors related to GPU memory). After the model was trained, inference did not run. 

In my command line, this shows up:

```
Started inference at: 2023-01-12 16:01:24.245652
Args:
{
2023-01-12 16:01:25.812233: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-12 16:01:26.260277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3987 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660, pci bus id: 0000:01:00.0, compute capability: 7.5
2023-01-12 16:01:26.996663: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-01-12 16:01:31.061993: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: -49 } dim { size: -50 } dim { size: -51 } dim { size: 1 } } } inputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -2 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "GPU" vendor: "NVIDIA" model: "NVIDIA GeForce GTX 1660" frequency: 1845 num_cores: 22 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 1572864 shared_memory_size_per_multiprocessor: 65536 memory_size: 4180672512 bandwidth: 192048000 } outputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: -52 } dim { size: -53 } dim { size: 1 } } }
2023-01-12 16:01:31.062585: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_UINT8 } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_UINT8 shape { dim { size: 4 } dim { size: 1080 } dim { size: 1920 } dim { size: 1 } } } inputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -2 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "CPU" vendor: "GenuineIntel" model: "101" frequency: 3600 num_cores: 8 environment { key: "cpu_instruction_set" value: "SSE, SSE2" } environment { key: "eigen" value: "3.3.90" } l1_cache_size: 32768 l2_cache_size: 262144 l3_cache_size: 6291456 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: -57 } dim { size: -58 } dim { size: 1 } } }
2023-01-12 16:01:31.068730: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: -99 } dim { size: -100 } dim { size: -101 } dim { size: 1 } } } inputs { dtype: DT_FLOAT shape { dim { size: -6 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -6 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "GPU" vendor: "NVIDIA" model: "NVIDIA GeForce GTX 1660" frequency: 1845 num_cores: 22 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 1572864 shared_memory_size_per_multiprocessor: 65536 memory_size: 4180672512 bandwidth: 192048000 } outputs { dtype: DT_FLOAT shape { dim { size: -6 } dim { size: -102 } dim { size: -103 } dim { size: 1 } } }
2023-01-12 16:01:31.716121: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8201
2023-01-12 16:01:33.158772: W tensorflow/core/common_runtime/bfc_allocator.cc:338] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
Traceback (most recent call last):
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\Scripts\sleap-track-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.2.8', 'console_scripts', 'sleap-track')())
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 4660, in main
    labels_pr = predictor.predict(provider)
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 440, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 2315, in _make_labeled_frames_from_generator
    for ex in generator:
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 399, in _predict_generator
    flush=True,
OSError: [Errno 22] Invalid argument
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\gui\learning\dialog.py", line 598, in run
    items_for_inference=items_for_inference,
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\gui\learning\runners.py", line 565, in run_learning_pipeline
    new_labeled_frame_count = run_gui_inference(inference_task, items_for_inference)
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\gui\learning\runners.py", line 779, in run_gui_inference
    gui=gui,
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\gui\learning\runners.py", line 298, in predict_subprocess
    line = line.decode().rstrip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 57: invalid continuation byte


### **My personal setup**

**Environments:**
SLEAP: 1.2.8
TensorFlow: 2.6.3
Numpy: 1.19.5
Python: 3.7.12
OS: Windows-10-10.0.19041-SP0

**GPU support:**
GPUs: 1/1 available
Device: /physical_device:GPU:0
Available: True
Initalized: False
Memory growth: None
```

### **Screenshots**

After the model is trained, SLEAP freezes:

![Inference](https://user-images.githubusercontent.com/99984451/212124955-bdd3d6eb-5baf-4845-8e64-e1c2bed234b3.png)

### **Data**

[Video and project.zip](https://github.com/talmolab/sleap/files/10410891/Video.and.project.zip)
(Can't upload the models because of the file size)

**Comment by talmo** [comment]
Hi @anarac97,

Just giving you a heads up that we're having a lab-wide event this week and will be a bit slower in responding to support requests.

In the meantime, just a couple of quick suggestions:
- Try [re-encoding your video](https://sleap.ai/help.html#does-my-data-need-to-be-in-a-particular-format).
- Try the top-down model type. This is for multiple animals but also works for a single animal and should actually work well for your data since the fly is small relative to the size of the images.

If the first suggestion doesn't work, we might need to dig into it -- this error message is a new one so this is likely a weird bug we haven't encountered before.

We'll check back in next week when we're back to regular operations :)

Cheers,

Talmo

**Comment by anarac97** [comment]
Hi Talmo, 

No worries, thanks for the notice and for the advice. Gonna try these suggestions and I'll let you know if the problem remains.

Cheers,
Rita

**Comment by anarac97** [comment]
Hi again Talmo,

Already tried re-encoding my video and using the top-down approach and it didn't help...

The command line shows:

Started inference at: 2023-01-20 13:54:36.815748
Args:
{
2023-01-20 13:54:38.263160: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-20 13:54:38.692320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3987 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660, pci bus id: 0000:01:00.0, compute capability: 7.5
2023-01-20 13:54:39.575593: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-01-20 13:54:44.907815: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: -49 } dim { size: -50 } dim { size: -51 } dim { size: 1 } } } inputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -2 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "GPU" vendor: "NVIDIA" model: "NVIDIA GeForce GTX 1660" frequency: 1845 num_cores: 22 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 1572864 shared_memory_size_per_multiprocessor: 65536 memory_size: 4180672512 bandwidth: 192048000 } outputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: -52 } dim { size: -53 } dim { size: 1 } } }
2023-01-20 13:54:44.908543: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_UINT8 } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_UINT8 shape { dim { size: 4 } dim { size: 1080 } dim { size: 1920 } dim { size: 1 } } } inputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -2 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "CPU" vendor: "GenuineIntel" model: "101" frequency: 3600 num_cores: 8 environment { key: "cpu_instruction_set" value: "SSE, SSE2" } environment { key: "eigen" value: "3.3.90" } l1_cache_size: 32768 l2_cache_size: 262144 l3_cache_size: 6291456 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: -57 } dim { size: -58 } dim { size: 1 } } }
2023-01-20 13:54:44.913635: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: -99 } dim { size: -100 } dim { size: -101 } dim { size: 1 } } } inputs { dtype: DT_FLOAT shape { dim { size: -6 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -6 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "GPU" vendor: "NVIDIA" model: "NVIDIA GeForce GTX 1660" frequency: 1845 num_cores: 22 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 1572864 shared_memory_size_per_multiprocessor: 65536 memory_size: 4180672512 bandwidth: 192048000 } outputs { dtype: DT_FLOAT shape { dim { size: -6 } dim { size: -102 } dim { size: -103 } dim { size: 1 } } }
2023-01-20 13:54:45.645484: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8201
2023-01-20 13:54:47.306897: W tensorflow/core/common_runtime/bfc_allocator.cc:338] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
Traceback (most recent call last):
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\Scripts\sleap-track-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.2.8', 'console_scripts', 'sleap-track')())
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 4660, in main
    labels_pr = predictor.predict(provider)
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 440, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 2315, in _make_labeled_frames_from_generator
    for ex in generator:
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 399, in _predict_generator
    flush=True,
OSError: [Errno 22] Invalid argument
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\gui\learning\dialog.py", line 598, in run
    items_for_inference=items_for_inference,
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\gui\learning\runners.py", line 565, in run_learning_pipeline
    new_labeled_frame_count = run_gui_inference(inference_task, items_for_inference)
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\gui\learning\runners.py", line 779, in run_gui_inference
    gui=gui,
  File "C:\Users\Lab2.3\miniconda3\envs\sleap\lib\site-packages\sleap\gui\learning\runners.py", line 298, in predict_subprocess
    line = line.decode().rstrip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 57: invalid continuation byte


and SLEAP freezes again:


![1](https://user-images.githubusercontent.com/99984451/214034324-8d83aa42-c336-4f1e-b07a-f4c78487b9f1.png)

![2](https://user-images.githubusercontent.com/99984451/214034346-7eb5025a-9dd0-4afc-be51-f88eb1754fa0.png)


Any idea of what I should do next?

Thanks a lot,
Rita

**Comment by roomrys** [comment]
This is going to be a tricky one to troubleshoot since we can't reproduce this bug, but a workaround for now would be:

1. Run training without inference (set the **Predict on** box to **none**)
2. Try tracking via the CLI: `sleap-track -m "models/model_folder" labels.v001.slp -o predictions.v001.slp`.
3. You can then import the predictions in the GUI to merge them in with your labels via the **File** -> **Merge into project...** option.

We can follow up with more bug hunting instructions so that you don't have to use this workaround, but let us know if that works for the moment.

**Comment by topohl** [comment]
Had the same issue- (excatly the same error message). It seems like having the .slp file with labels on a server produced this error. Copying the .slp file and storing it locally solved the issue with inference not working. Training, on the other hand, worked just fine with the .slp file on the server.

**Comment by talmo** [comment]
For future reference: this might also just have to do with the terminal emulator being used. Typically not an issue in non-interactive jobs on clusters, but sometimes it's a problem.

Trying to set `--verbosity none` might also help as it will disable progress printing which uses unicode characters which the terminal might not support.
