### ISSUE TITLE
Videos not appearing in the video window

### ISSUE THREAD

**Issue by lragel1992** [talmolab/sleap#1152]
# Bug description
My project opens but the video files fail to load.

## Expected behaviour
I expected 46 videos to load with file names to appear.

## Actual behaviour
Only one video appears with labels and predictions. 45 video files are missing from the project.

## Your personal set up
Device name	RBIOB-LRAGEL
Processor	11th Gen Intel(R) Core(TM) i7-11375H @ 3.30GHz   3.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	6070C271-2BC0-418A-AF69-3F66820B03BD
Product ID	00326-10000-00000-AA696
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

- OS:

- Version(s):

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [M1 Macs](https://sleap.ai/installation.html#m1-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```
(base) C:\Windows\System32>conda activate sleap_1.2.9

(sleap_1.2.9) C:\Windows\System32>sleap-label
Saving config: C:\Users\Lauren Ragel/.sleap/1.2.9/preferences.yaml

Software versions:
SLEAP: 1.2.9
TensorFlow: 2.6.3
Numpy: 1.19.5
Python: 3.7.12
OS: Windows-10-10.0.22621-SP0

Happy SLEAPing! :)
Traceback (most recent call last):
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\commands.py", line 262, in openProject
    self.execute(OpenProject, filename=filename, first_open=first_open)
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\commands.py", line 240, in execute
    command().execute(context=self, params=kwargs)
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\commands.py", line 137, in execute
    self.do_with_signal(context, params)
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\commands.py", line 161, in do_with_signal
    cls.do_action(context, params)
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\commands.py", line 605, in do_action
    context.app.loadProjectFile(filename)
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\app.py", line 1496, in loadProjectFile
    self.loadLabelsObject(labels, filename)
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\app.py", line 1527, in loadLabelsObject
    self.on_data_update([UpdateTopic.project, UpdateTopic.all])
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\app.py", line 1322, in on_data_update
    self.videosTable.model().items = self.labels.videos
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\dataviews.py", line 102, in items
    item_data = self.item_to_data(obj, item)
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\dataviews.py", line 362, in item_to_data
    return {key: getattr(item, key) for key in self.properties}
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\gui\dataviews.py", line 362, in <dictcomp>
    return {key: getattr(item, key) for key in self.properties}
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\io\video.py", line 1029, in __getattr__
    return getattr(self.backend, item)
  File "C:\Miniconda3\envs\sleap_1.2.9\lib\site-packages\sleap\io\video.py", line 256, in channels
    return self.__dataset_h5.shape[self.__channel_idx]
IndexError: tuple index out of range
Unable to load video with these parameters. Error: No name (no name)
Unable to load video with these parameters. Error: No name (no name)
Unable to load video with these parameters. Error: No name (no name)
Unable to load video with these parameters. Error: No name (no name)
Unable to load video with these parameters. Error: No name (no name)
Unable to load video with these parameters. Error: No name (no name)
Unable to load video with these parameters. Error: No name (no name)
Unable to load video with these parameters. Error: No name (no name)

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```

</details>

## Screenshots

![image](https://user-images.githubusercontent.com/123604594/214719066-388a604c-4e1d-4c8b-9996-4d6887d7d922.png)

## How to reproduce
Go to open project, select project name, and videos fail to load.

**Comment by roomrys** [comment]
Hi @lragel1992,

This looks like a similar problem to #747 where at least one video file was corrupted. Can you check your terminal for any errors? Where are your videos from? Is it possible they were corrupted during the download?

Thanks,
Liezl

**Comment by lragel1992** [comment]
Hi Liezl,


Actually I moved these files to an external hard drive temporarily to save space, but moved the same files back to my C:\ local drive on my laptop shortly thereafter. Thankfully, the same files are backed up to a server as well so I will try to copy them into my local drive from there. Hopefully this will resolve the issue.


Thank you,

Lauren

________________________________

**Comment by roomrys** [comment]
Hi @lragel1992 ,

I realize you are replying via email which isn't sending you updates when I edit the same comment on Github. After a bit more investigation, we think the problem might be related to your preprocessing.

Thanks,
Liezl
