### ISSUE TITLE
can't load(import) videos

### ISSUE THREAD

**Issue by mohamedalyzahran** [talmolab/sleap#1154]
# Bug description

can't load videos

## Expected behaviour

when i try to impot video it doesn't import anything and gives me this error

```
Software versions:
SLEAP: 1.2.9
TensorFlow: 2.6.3
Numpy: 1.19.5
Python: 3.7.12
OS: Windows-10-10.0.19041-SP0

Happy SLEAPing! :)
Unable to load video with these parameters. Error: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/Desktop/RI basal/CNO3.mp4', grayscale=False, bgr=True, dataset='', input_format='')."
Unable to load video with these parameters. Error: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/Desktop/RI basal/CNO3.mp4', grayscale=True, bgr=True, dataset='', input_format='')."
Error occurred during callback 0 for video!
[<bound method QtVideoPlayer.load_video of <sleap.gui.widgets.video.QtVideoPlayer(0x1e0dab38630) at 0x000001E0E4420688>>, <function MainWindow._create_video_player.<locals>.switch_frame at 0x000001E0E45C69D8>, <function MainWindow._create_video_player.<locals>.<lambda> at 0x000001E0E45C6AF8>, <function MainWindow._create_video_player.<locals>.update_frame_chunk_suggestions at 0x000001E0E45C6A68>]
"Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/Desktop/RI basal/CNO3.mp4', grayscale=True, bgr=True, dataset='', input_format='')."
Traceback (most recent call last):
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 390, in addVideo
    self.execute(AddVideo)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 240, in execute
    command().execute(context=self, params=kwargs)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 137, in execute
    self.do_with_signal(context, params)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 163, in do_with_signal
    context.signal_update(cls.topics)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 213, in signal_update
    self.update_callback(what)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\app.py", line 1322, in on_data_update
    self.videosTable.model().items = self.labels.videos
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 102, in items
    item_data = self.item_to_data(obj, item)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 362, in item_to_data
    return {key: getattr(item, key) for key in self.properties}
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 362, in <dictcomp>
    return {key: getattr(item, key) for key in self.properties}
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 1029, in __getattr__
    return getattr(self.backend, item)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 457, in height
    return self.test_frame.shape[0]
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 407, in test_frame
    self._test_frame_ = self.get_frame(0, grayscale=False)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 492, in get_frame
    raise KeyError(f"Unable to load frame {idx} from {self}.")
KeyError: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/Desktop/RI basal/CNO3.mp4', grayscale=True, bgr=True, dataset='', input_format='')."
```

 -->

- OS:
Win 10N
- Version(s):
SLEAP v1.2.9,
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [M1 Macs](https://sleap.ai/installation.html#m1-macs)

**Comment by roomrys** [comment]
Hi @mohamedalyzahran ,

This is most likely due to the video not being in a seekable format. [Check out this section of our help page](https://sleap.ai/help.html#does-my-data-need-to-be-in-a-particular-format) and let us know if re-encoding doesn't solve the problem for you.

Cheers,

Liezl

**Comment by mohamedalyzahran** [comment]
Hi roomrys,

I did the re-encoding as you suggested but still have the same error with the new encoded video 

Happy SLEAPing! :)
Unable to load video with these parameters. Error: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/output.mp4', grayscale=False, bgr=True, dataset='', input_format='')."
Unable to load video with these parameters. Error: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/output.mp4', grayscale=True, bgr=True, dataset='', input_format='')."
Error occurred during callback 0 for video!
[<bound method QtVideoPlayer.load_video of <sleap.gui.widgets.video.QtVideoPlayer(0x2b4202cc9f0) at 0x000002B429AE96C8>>, <function MainWindow._create_video_player.<locals>.switch_frame at 0x000002B429C8B9D8>, <function MainWindow._create_video_player.<locals>.<lambda> at 0x000002B429C8BAF8>, <function MainWindow._create_video_player.<locals>.update_frame_chunk_suggestions at 0x000002B429C8BA68>]
"Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/output.mp4', grayscale=True, bgr=True, dataset='', input_format='')."
Traceback (most recent call last):
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 390, in addVideo
    self.execute(AddVideo)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 240, in execute
    command().execute(context=self, params=kwargs)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 137, in execute
    self.do_with_signal(context, params)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 163, in do_with_signal
    context.signal_update(cls.topics)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 213, in signal_update
    self.update_callback(what)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\app.py", line 1322, in on_data_update
    self.videosTable.model().items = self.labels.videos
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 102, in items
    item_data = self.item_to_data(obj, item)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 362, in item_to_data
    return {key: getattr(item, key) for key in self.properties}
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 362, in <dictcomp>
    return {key: getattr(item, key) for key in self.properties}
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 1029, in __getattr__
    return getattr(self.backend, item)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 457, in height
    return self.test_frame.shape[0]
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 407, in test_frame
    self._test_frame_ = self.get_frame(0, grayscale=False)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 492, in get_frame
    raise KeyError(f"Unable to load frame {idx} from {self}.")
KeyError: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/output.mp4', grayscale=True, bgr=True, dataset='', input_format='')."
Unable to load video with these parameters. Error: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/output.mp4', grayscale=False, bgr=True, dataset='', input_format='')."
Unable to load video with these parameters. Error: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/output.mp4', grayscale=True, bgr=True, dataset='', input_format='')."
Traceback (most recent call last):
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 390, in addVideo
    self.execute(AddVideo)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 240, in execute
    command().execute(context=self, params=kwargs)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 137, in execute
    self.do_with_signal(context, params)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 163, in do_with_signal
    context.signal_update(cls.topics)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 213, in signal_update
    self.update_callback(what)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\app.py", line 1322, in on_data_update
    self.videosTable.model().items = self.labels.videos
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 102, in items
    item_data = self.item_to_data(obj, item)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 362, in item_to_data
    return {key: getattr(item, key) for key in self.properties}
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 362, in <dictcomp>
    return {key: getattr(item, key) for key in self.properties}
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 1029, in __getattr__
    return getattr(self.backend, item)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 457, in height
    return self.test_frame.shape[0]
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 407, in test_frame
    self._test_frame_ = self.get_frame(0, grayscale=False)
  File "C:\Users\moham\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 492, in get_frame
    raise KeyError(f"Unable to load frame {idx} from {self}.")
KeyError: "Unable to load frame 0 from MediaVideo(filename='C:/Users/moham/output.mp4', grayscale=True, bgr=True, dataset='', input_format='')."

**Comment by roomrys** [comment]
Hi @mohamedalyzahran,

Would you mind sharing the problematic video with me at [lmaree@salk.edu](mailto:lmaree@salk.edu). It might be nice to have access to the .slp as well if you can.

Thanks,
Liezl

**Comment by roomrys** [comment]
I am closing this issue due to inactivity - if anyone is still experiencing this issue, please post a log and let us know!
