### ISSUE TITLE
SLEAP with Radeon GPU 

### ISSUE THREAD

**Issue by fasalman** [talmolab/sleap#1263]
# Bug description

I am looking to use SLEAP with an AMD Radeon GPU. I saw [this article](https://urldefense.com/v3/__https://learn.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-plugin__;!!GX6Nv3_Pjr8b-17qtCok029Ok438DqXQ!xrgKsT5QOop1dINUnm3r-XhhcPmwpGG_39CElo2xBPL_lKAbKu48ZZDSQZjrhyoPnjX5qaQlvL3ScALWscJ-$) describe a package to make tensorflow compatible with Radeon GPUs. It has some dependency incompatibilities that could be addressed in a Radeon specific SLEAP installation, as tensorflow was able to detect my GPU. 

## Expected behaviour

SLEAP GUI would show

## Actual behaviour

SLEAP GUI did not show, command line listed errors of packages of the wrong version. 

## Your personal set up

- OS: Windows-10-10.0.19041-SP0
- Version(s):
SLEAP: 1.3.0
TensorFlow: 2.6.3
Numpy: 1.19.5
Python: 3.7.12
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [X ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
aom                       3.5.0                h63175ca_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.4                    pypi_0    pypi
cattrs                    1.1.1                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
clang                     5.0                      pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cuda-nvcc                 11.3.58              hb8d16a4_0    nvidia
cudatoolkit               11.3.1              hf2f0253_11    conda-forge
cudnn                     8.2.1.32             h754d62a_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
efficientnet              1.0.0                    pypi_0    pypi
expat                     2.5.0                h63175ca_1    conda-forge
ffmpeg                    5.1.2           gpl_h5b1d025_106    conda-forge
flatbuffers               23.3.3                   pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h546665d_1    conda-forge
gast                      0.4.0                    pypi_0    pypi
geos                      3.9.1                h39d44d4_2    conda-forge
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.44.0                   pypi_0    pypi
h5py                      3.1.0           nompi_py37h19fda09_100    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
hdmf                      3.5.2                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
image-classifiers         1.0.0                    pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
imgstore                  0.2.9                    pypi_0    pypi
importlib-metadata        4.11.1                   pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   hcfcfb64_3    conda-forge
jsmin                     3.0.1                    pypi_0    pypi
jsonpickle                1.2                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
keras                     2.10.0                   pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  16.0.0                   pypi_0    pypi
libdeflate                1.10                 h8ffe710_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libhwloc                  2.9.0                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libtiff                   4.3.0                hc4061b1_4    conda-forge
libxml2                   2.10.3               hc3477c8_6    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.6                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
ndx-pose                  0.1.1                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
nixio                     1.5.3                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.5.5.62                 pypi_0    pypi
opencv-python-headless    4.5.5.62                 pypi_0    pypi
openh264                  2.3.1                h63175ca_2    conda-forge
openjpeg                  2.5.0                hb211442_0    conda-forge
openssl                   3.1.0                hcfcfb64_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5            py37h9386db6_0    conda-forge
pillow                    8.4.0            py37hd7d9ad0_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pykalman                  0.9.5                    pypi_0    pypi
pynwb                     2.3.1                    pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
pyreadline                2.1             py37h03978a9_1006    conda-forge
pyrsistent                0.19.3                   pypi_0    pypi
pyside2                   5.14.1                   pypi_0    pypi
python                    3.7.12          h900ac77_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-rapidjson          1.10                     pypi_0    pypi
python_abi                3.7                     3_cp37m    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyzmq                     25.0.2                   pypi_0    pypi
qimage2ndarray            1.9.0                    pypi_0    pypi
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      10.16.1                  pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.7.3            py37hb6553fb_0    conda-forge
seaborn                   0.12.2                   pypi_0    pypi
segmentation-models       1.0.1                    pypi_0    pypi
setuptools                59.8.0           py37h03978a9_1    conda-forge
setuptools-scm            6.4.2                    pypi_0    pypi
shapely                   1.7.1            py37hc520ffa_5    conda-forge
shiboken2                 5.14.1                   pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sleap                     1.3.0                    pypi_0    pypi
sqlite                    3.40.0               hcfcfb64_0    conda-forge
svt-av1                   1.4.1                h63175ca_0    conda-forge
tbb                       2021.8.0             h91493d7_0    conda-forge
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.6.3                    pypi_0    pypi
tensorflow-cpu            2.10.0                   pypi_0    pypi
tensorflow-directml-plugin 0.4.0.dev230202          pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-hub            0.13.0                   pypi_0    pypi
tensorflow-intel          2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
typing-extensions         3.10.0.2                 pypi_0    pypi
tzdata                    2022.7                   pypi_0    pypi
tzlocal                   4.3                      pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
```

</details>

<details><summary>Logs</summary>

Traceback (most recent call last):
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tensorboard 2.10.1 (c:\users\f\.conda\envs\sleap\lib\site-packages), Requirement.parse('tensorboard<2.7,>=2.6.0'), {'tensorflow'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\f\.conda\envs\sleap\Scripts\sleap-diagnostic-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.0', 'console_scripts', 'sleap-diagnostic')())
  File "C:\Users\f\.conda\envs\sleap\Scripts\sleap-diagnostic-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\importlib_metadata\__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "C:\Users\f\.conda\envs\sleap\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\sleap\__init__.py", line 10, in <module>
    from sleap.io.dataset import Labels, load_file
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\sleap\io\dataset.py", line 71, in <module>
    from sleap.instance import (
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\sleap\instance.py", line 32, in <module>
    from sleap.io.video import Video
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\sleap\io\video.py", line 17, in <module>
    from sleap.util import json_loads, json_dumps
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\sleap\util.py", line 22, in <module>
    from pkg_resources import Requirement, resource_filename
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 3266, in <module>
    @_call_aside
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Users\f\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tensorboard<2.7,>=2.6.0' distribution was not found and is required by tensorflow

```
# paste relevant logs here, if any
https://github.com/talmolab/sleap/files/11162527/sleap.txt
```

</details>

## How to reproduce

1. conda create -y -n sleap -c sleap -c nvidia -c conda-forge sleap=1.3.0
2. pip install tensorflow-directml-plugin

**Comment by talmo** [comment]
Hi @fasalman — apologies for the very long delay on this.

Since this was filed, SLEAP has migrated its training/inference stack from
TensorFlow to PyTorch in `sleap-nn`. The original
`tensorflow-directml-plugin` dependency-conflict path you hit no longer
exists in current versions of SLEAP.

The shape of AMD GPU support today:

- **Windows / DirectML inference:** sleap-nn's ONNX export path already
  supports running on AMD GPUs via DirectML (`DmlExecutionProvider`). If
  you export your model to ONNX, you can run inference on a Radeon GPU on
  Windows.
- **Native PyTorch on AMD:** Not wired up yet. PyTorch publishes ROCm
  wheels for Linux, but sleap-nn's package metadata only exposes CPU and
  CUDA build variants today.

I'm tracking the work to fill in native AMD support over at
**talmolab/sleap-nn#569** — closing this here so we can centralize
discussion in the active repo. Thanks for the original report!
