### ISSUE TITLE
Can't train with leap TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by e-velin** [talmolab/sleap#1322]
# Bug description
Hi, I'm trying to do the training on my labelled dataset with the leap model 

## Actual behaviour

I keep getting the error: `  File "/Users/evelin/sleap/sleap/gui/learning/scopedkeydict.py", line 39, in set_hierarchical_key_val
    current_dict[key] = val
TypeError: 'NoneType' object does not support item assignment`. 
I used this model before on a different dataset and it worked and on this dataset e.g. training with unet works. 
## Your personal set up

- OS: macOS 13.3.1

- Version(s):
 SLEAP v1.2.9, python 3.9.15
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [x ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [x] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>

</details>

<details><summary>Logs</summary>

</details>

## How to reproduce

in GUI:
1. Go to 'Predict'
2. Click on 'Run Training'
3. At Training Pipeline, Training/Inference Pipeline Type Scroll down to 'single animal'. 
4. At Single Instance Model Configuration choose: Model: Backbone: leap
5. See error

**Comment by roomrys** [comment]
Hi @e-velin,

Thanks for creating a write-up. This seems to be an error in our code that gets the info from the Training/Inference GUI to create a training_config.json. It seems that `set_hierarchical_key_val current_dict[key] = None` for that particular `key`... I was hoping to ask you for a `Traceback` that might help me determine which `key` is causing the problem.

Thanks,
Liezl

**Comment by e-velin** [comment]
Hi @roomrys, 

This is the full Traceback I receive when trying to train with the leap model:

Traceback (most recent call last):
  File "/Users/evelin/sleap/sleap/gui/learning/dialog.py", line 606, in run
  File "/Users/evelin/sleap/sleap/gui/learning/dialog.py", line 458, in get_every_head_config_data
  File "/Users/evelin/sleap/sleap/gui/learning/scopedkeydict.py", line 192, in make_training_config_from_key_val_dict
  File "/Users/evelin/sleap/sleap/gui/learning/scopedkeydict.py", line 51, in to_hierarchical_dict
  File "/Users/evelin/sleap/sleap/gui/learning/scopedkeydict.py", line 45, in set_hierarchical_key_val
  File "/Users/evelin/sleap/sleap/gui/learning/scopedkeydict.py", line 45, in set_hierarchical_key_val
  File "/Users/evelin/sleap/sleap/gui/learning/scopedkeydict.py", line 45, in set_hierarchical_key_val
  File "/Users/evelin/sleap/sleap/gui/learning/scopedkeydict.py", line 39, in set_hierarchical_key_val
TypeError: 'NoneType' object does not support item assignment

**Comment by talmo** [comment]
We will be fixing this (among other issues) once we implemented our new neural network backend. Feel free to let us know if you run into any other issues!
