### ISSUE TITLE
Running SLEAP on a remote cluster using training_job package doesn't work

### ISSUE THREAD

**Issue by elhananby** [talmolab/sleap#1339]
## Bug description
I am trying to train SLEAP on our institute cluster. After setting up the conda env. and transferring the ``labels.v001.slp.training_job`` file to the remote machine, I am unable to start the training - either due to a ``UnicodeDecodeError`` or ``TypeError`` errors.

I suspect it might be because the remote machine cannot access the videos used for labeling, but I am not sure.

## Expected behaviour
Initialize training on labeled data.

## Actual behaviour
If I just try to run ``sleap-train labels.v001.slp.training_job.zip``, the output is:
```
INFO:numexpr.utils:Note: NumExpr detected 48 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/bin/sleap-train", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.0', 'console_scripts', 'sleap-train')())
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/training.py", line 2013, in main
    trainer = create_trainer_using_cli(args=args)
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/training.py", line 1923, in create_trainer_using_cli
    job_config = TrainingJobConfig.load_json(job_filename)
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/config/training_job.py", line 120, in load_json
    json_data = f.read()
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 10: invalid start byte
```
If instead I run ``./train-script.sh``:
```
./train-script.sh 
INFO:numexpr.utils:Note: NumExpr detected 48 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:sleap.nn.training:Versions:
SLEAP: 1.3.0
TensorFlow: 2.6.3
Numpy: 1.19.5
Python: 3.7.12
OS: Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.9.2009-Core
INFO:sleap.nn.training:Training labels file: labels.v001.slp
INFO:sleap.nn.training:Training profile: single_instance.json
INFO:sleap.nn.training:
INFO:sleap.nn.training:Arguments:
INFO:sleap.nn.training:{
    "training_job_path": "single_instance.json",
    "labels_path": "labels.v001.slp",
    "video_paths": [
        ""
    ],
    "val_labels": null,
    "test_labels": null,
    "base_checkpoint": null,
    "tensorboard": false,
    "save_viz": false,
    "zmq": false,
    "run_name": "",
    "prefix": "",
    "suffix": "",
    "cpu": false,
    "first_gpu": false,
    "last_gpu": false,
    "gpu": "auto"
}
INFO:sleap.nn.training:
INFO:sleap.nn.training:Training job:
INFO:sleap.nn.training:{
    "data": {
        "labels": {
            "training_labels": null,
            "validation_labels": null,
            "validation_fraction": 0.1,
            "test_labels": null,
            "split_by_inds": false,
            "training_inds": null,
            "validation_inds": null,
            "test_inds": null,
            "search_path_hints": [],
            "skeletons": []
        },
        "preprocessing": {
            "ensure_rgb": false,
            "ensure_grayscale": false,
            "imagenet_mode": null,
            "input_scaling": 1.0,
            "pad_to_stride": null,
            "resize_and_pad_to_target": true,
            "target_height": null,
            "target_width": null
        },
        "instance_cropping": {
            "center_on_part": null,
            "crop_size": null,
            "crop_size_detection_padding": 16
        }
    },
    "model": {
        "backbone": {
            "leap": null,
            "unet": {
                "stem_stride": null,
                "max_stride": 16,
                "output_stride": 2,
                "filters": 16,
                "filters_rate": 2.0,
                "middle_block": true,
                "up_interpolate": true,
                "stacks": 1
            },
            "hourglass": null,
            "resnet": null,
            "pretrained_encoder": null
        },
        "heads": {
            "single_instance": {
                "part_names": null,
                "sigma": 1.0,
                "output_stride": 2,
                "loss_weight": 1.0,
                "offset_refinement": false
            },
            "centroid": null,
            "centered_instance": null,
            "multi_instance": null,
            "multi_class_bottomup": null,
            "multi_class_topdown": null
        },
        "base_checkpoint": null
    },
    "optimization": {
        "preload_data": true,
        "augmentation_config": {
            "rotate": true,
            "rotation_min_angle": -15.0,
            "rotation_max_angle": 15.0,
            "translate": false,
            "translate_min": -5,
            "translate_max": 5,
            "scale": true,
            "scale_min": 0.9,
            "scale_max": 1.1,
            "uniform_noise": false,
            "uniform_noise_min_val": 0.0,
            "uniform_noise_max_val": 10.0,
            "gaussian_noise": true,
            "gaussian_noise_mean": 5.0,
            "gaussian_noise_stddev": 1.0,
            "contrast": false,
            "contrast_min_gamma": 0.5,
            "contrast_max_gamma": 2.0,
            "brightness": false,
            "brightness_min_val": 0.0,
            "brightness_max_val": 10.0,
            "random_crop": false,
            "random_crop_height": 256,
            "random_crop_width": 256,
            "random_flip": true,
            "flip_horizontal": false
        },
        "online_shuffling": true,
        "shuffle_buffer_size": 128,
        "prefetch": true,
        "batch_size": 4,
        "batches_per_epoch": null,
        "min_batches_per_epoch": 200,
        "val_batches_per_epoch": null,
        "min_val_batches_per_epoch": 10,
        "epochs": 200,
        "optimizer": "adam",
        "initial_learning_rate": 0.0001,
        "learning_rate_schedule": {
            "reduce_on_plateau": true,
            "reduction_factor": 0.5,
            "plateau_min_delta": 1e-06,
            "plateau_patience": 5,
            "plateau_cooldown": 3,
            "min_learning_rate": 1e-08
        },
        "hard_keypoint_mining": {
            "online_mining": false,
            "hard_to_easy_ratio": 2.0,
            "min_hard_keypoints": 2,
            "max_hard_keypoints": null,
            "loss_scale": 5.0
        },
        "early_stopping": {
            "stop_training_on_plateau": true,
            "plateau_min_delta": 1e-08,
            "plateau_patience": 10
        }
    },
    "outputs": {
        "save_outputs": true,
        "run_name": "230606_164504",
        "run_name_prefix": "",
        "run_name_suffix": ".single_instance",
        "runs_folder": "models",
        "tags": [
            ""
        ],
        "save_visualizations": true,
        "delete_viz_images": true,
        "zip_outputs": false,
        "log_to_csv": true,
        "checkpointing": {
            "initial_model": false,
            "best_model": true,
            "every_epoch": false,
            "latest_model": false,
            "final_model": false
        },
        "tensorboard": {
            "write_logs": false,
            "loss_frequency": "epoch",
            "architecture_graph": false,
            "profile_graph": false,
            "visualizations": true
        },
        "zmq": {
            "subscribe_to_controller": false,
            "controller_address": "tcp://127.0.0.1:9000",
            "controller_polling_timeout": 10,
            "publish_updates": false,
            "publish_address": "tcp://127.0.0.1:9001"
        }
    },
    "name": "",
    "description": "",
    "sleap_version": "1.3.0",
    "filename": "single_instance.json"
}
INFO:sleap.nn.training:
INFO:sleap.nn.training:Auto-selected GPU 0 with 22687 MiB of free memory.
INFO:sleap.nn.training:Using GPU 0 for acceleration.
INFO:sleap.nn.training:Disabled GPU memory pre-allocation.
INFO:sleap.nn.training:System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
INFO:sleap.nn.training:
INFO:sleap.nn.training:Initializing trainer...
INFO:sleap.nn.training:Loading training labels from: labels.v001.slp
INFO:sleap.nn.training:Creating training and validation splits from validation fraction: 0.1
INFO:sleap.nn.training:  Splits: Training = 135 / Validation = 15.
INFO:sleap.nn.training:Setting up for training...
INFO:sleap.nn.training:Setting up pipeline builders...
INFO:sleap.nn.training:Setting up model...
INFO:sleap.nn.training:Building test pipeline...
Traceback (most recent call last):
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/bin/sleap-train", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.0', 'console_scripts', 'sleap-train')())
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/training.py", line 2014, in main
    trainer.train()
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/training.py", line 926, in train
    self.setup()
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/training.py", line 912, in setup
    self._setup_model()
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/training.py", line 727, in _setup_model
    self.data_readers.training_labels_reader
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/data/pipelines.py", line 364, in make_base_pipeline
    provider=data_provider,
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/data/resizing.py", line 324, in from_config
    max_height, max_width = provider.max_height_and_width
  File "/gpfs/soma_fs/home/buchsbaum/.conda/envs/sleap/lib/python3.7/site-packages/sleap/nn/data/providers.py", line 140, in max_height_and_width
    return max(video.shape[1] for video in self.videos), max(
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

## Your personal set up
Labeling is done on my persoanl PC, with Ubuntu 20.04, and SLEAP 1.3.0

Training is done on a remote machine on our cluster via SSH:
- OS: CentOS Linux 7 (Core)
- Version(s): SLEAP v1.3.0, python 3.7
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [X] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>
```
absl-py==0.15.0
astunparse==1.6.3
attrs==21.2.0
backports.zoneinfo==0.2.1
Bottleneck @ file:///home/conda/feedstock_root/build_artifacts/bottleneck_1656803757560/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools==4.2.4
cattrs==1.1.1
certifi==2021.10.8
charset-normalizer==2.0.12
clang==5.0
colorama==0.4.6
commonmark==0.9.1
cycler==0.11.0
efficientnet==1.0.0
flatbuffers==1.12
fonttools==4.38.0
gast==0.4.0
google-auth==1.35.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.44.0
h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1604753641401/work
hdmf==3.5.2
idna==3.3
image-classifiers==1.0.0
imageio==2.15.0
imgaug==0.4.0
imgstore==0.2.9
importlib-metadata==4.11.1
importlib-resources==5.12.0
joblib==1.2.0
jsmin==3.0.1
jsonpickle==1.2
jsonschema==4.17.3
keras==2.6.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
Markdown==3.3.6
matplotlib==3.5.3
ndx-pose==0.1.1
networkx==2.6.3
nixio==1.5.3
numexpr @ file:///croot/numexpr_1668713893690/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1649281349439/work
oauthlib==3.2.0
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
opencv-python @ git+https://github.com/talmolab/wrap_opencv-python-headless.git@ede49f6a23a73033216339f29515e59d594ba921
opencv-python-headless==4.5.5.62
opt-einsum==3.3.0
packaging==21.3
pandas==1.3.5
Pillow==8.4.0
pkgutil_resolve_name==1.3.10
protobuf==3.19.4
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.14.0
pykalman==0.9.5
pynwb==2.3.1
pyparsing==3.0.6
pyrsistent==0.19.3
PySide2==5.14.1
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-rapidjson==1.10
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.3.0
PyYAML==6.0
pyzmq==25.0.2
qimage2ndarray==1.9.0
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1680148448366/work
requests==2.27.1
requests-oauthlib==1.3.1
rich==10.16.1
rsa==4.8
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-image==0.19.3
scikit-learn==1.0.2
scikit-video==1.1.11
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1637806658031/work
seaborn==0.12.2
segmentation-models==1.0.1
setuptools-scm==6.3.2
Shapely @ file:///home/conda/feedstock_root/build_artifacts/shapely_1628205363317/work
shiboken2==5.14.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
sleap==1.3.0
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.6.3
tensorflow-estimator==2.6.0
tensorflow-hub==0.13.0
termcolor==1.1.0
threadpoolctl==3.1.0
tifffile==2021.11.2
tomli==2.0.0
typing-extensions==3.10.0.2
tzdata==2022.7
tzlocal==4.3
urllib3==1.26.8
Werkzeug==2.0.3
wrapt==1.12.1
zipp==3.7.0

```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```

</details>

**Comment by elhananby** [comment]
NVM, I'm a dummy, didn't realize I needed to unzip the file before training. I thought the `sleap-train` accepts it directly.
after unzipping and running `sleap-train single_instance.json labels.v001.pkg.slp` it works perfectly.

**Comment by roomrys** [comment]
Hi @elhananby,

Glad you solved it! This helps us and others as well since users were getting a similar traceback of
```
    return max(video.shape[1] for video in self.videos), max(
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```
Hopefully this solves someone else's issue as well.

Thanks for posting!
Liezl
