### ISSUE TITLE
Installing sleap on apple silicon 

### ISSUE THREAD

**Issue by aam112** [talmolab/sleap#1345]
# Bug description

Issue installing SLEAP on M1 Mac

## Expected behaviour

Sleap installs after running "conda env create -f environment_apple_silicon.yml"

## Actual behaviour

Conda env exception: pip error... program crashes when trying to install pip dependencies

## Your personal set up

Trying to install sleap on an M1 Mac following the instructions listed on the website.

- OS: MacOS Monterey 12.6.6

- Version(s): SLEAP v1.3.0

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [x] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>

Conda List Output:

packages in environment at /Users/user1/miniconda3:

Name                    Version                   Build  Channel
boltons                   23.0.0          py310hca03da5_0  
brotlipy                  0.7.0           py310h1a28f6b_1002  
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2023.01.10           hca03da5_0  
certifi                   2022.12.7       py310hca03da5_0  
cffi                      1.15.1          py310h80987f9_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     23.3.1          py310hca03da5_0  
conda-content-trust       0.1.3           py310hca03da5_0  
conda-package-handling    2.0.2           py310hca03da5_0  
conda-package-streaming   0.7.0           py310hca03da5_0  
cryptography              39.0.1          py310h834c97f_0  
idna                      3.4             py310hca03da5_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
libffi                    3.4.2                hca03da5_6  
ncurses                   6.4                  h313beb8_0  
openssl                   1.1.1t               h1a28f6b_0  
packaging                 23.0            py310hca03da5_0  
pip                       23.0.1          py310hca03da5_0  
pluggy                    1.0.0           py310hca03da5_1  
pycosat                   0.6.4           py310h1a28f6b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0          py310hca03da5_0  
pysocks                   1.7.1           py310hca03da5_0  
python                    3.10.10              hc0d8a6c_2  
python.app                3               py310h1a28f6b_0  
readline                  8.2                  h1a28f6b_0  
requests                  2.28.1          py310hca03da5_1  
ruamel.yaml               0.17.21         py310h1a28f6b_0  
ruamel.yaml.clib          0.2.6           py310h1a28f6b_1  
setuptools                65.6.3          py310hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.1               h80987f9_0  
tk                        8.6.12               hb8d0fd4_0  
toolz                     0.12.0          py310hca03da5_0  
tqdm                      4.65.0          py310h33ce5c2_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.15         py310hca03da5_0  
wheel                     0.38.4          py310hca03da5_0  
xz                        5.2.10               h80987f9_1  
zlib                      1.2.13               h5a0b063_0  
zstandard                 0.19.0          py310h80987f9_0  

</details>

<details><summary>Logs</summary>

```
Here is the error code:

Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0



Downloading and Extracting Packages
                                                                                
Preparing transaction: done                                                     
Verifying transaction: done                                                     
Executing transaction: done                                                     
Installing pip dependencies: \ Ran pip subprocess with arguments:               
['/Users/user1/miniconda3/envs/sleap/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/user1/sleap/condaenv.snm5urdy.requirements.txt', '--exists-action=b']                                                 
Pip subprocess output:                                                          
Obtaining file:///Users/user1/sleap (from -r /Users/user1/sleap/condaenv.snm5urdy.requirements.txt (line 1))                        
  Preparing metadata (setup.py): started                                        
  Preparing metadata (setup.py): finished with status 'error'                   
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping                              
                                                                                
Pip subprocess error:                                                           
  error: subprocess-exited-with-error                                           
                                                                                
  × python setup.py egg_info did not run successfully.                          
  │ exit code: 1      
  ╰─> [52 lines of output]
      /Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools-scm/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools-scm/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools-scm/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools-scm/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools-scm/
      ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
      ERROR: No matching distribution found for setuptools_scm
      Traceback (most recent call last):
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/user1/miniconda3/envs/sleap/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/5t/rn00b2w931d4wm3bq2m2f3m80000gp/T/tmp2ljv_a32', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/user1/sleap/setup.py", line 29, in <module>
          setup(
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/Users/user1/miniconda3/envs/sleap/lib/python3.9/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/user1/miniconda3/envs/sleap/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/5t/rn00b2w931d4wm3bq2m2f3m80000gp/T/tmp2ljv_a32', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

</details>

## How to reproduce

Follow instructions up until point of installation of sleap - error occurs when running sleap installation

**Comment by roomrys** [comment]
Hi @aam112,

I see you've closed the issue. Were you able to complete the installation?

Thanks,
Liezl
