### ISSUE TITLE
Installation via conda package

### ISSUE THREAD

**Issue by GarrettBlair** [talmolab/sleap#1362]
# Bug description

After successful installation via the [conda package](https://sleap.ai/installation.html#conda-package), after activating the env and attempting to open the GUI `sleap-label` results in failure. [Direct installation](https://sleap.ai/installation.html#conda-from-source) worked fine, and the GUI opens as expected.

## Expected behaviour

Running `sleap-label` after install via conda package and env activation should open the gui

## Actual behaviour

GUI fails to load and an error is given

## Your personal set up

- OS:
Windows 11, NVIDIA 3080
- Version(s):
SLEAP v1.3.0 via conda package and v1.3.1 via conda from source

(From GUI)
SLEAP: 1.3.1
TensorFlow: 2.8.4
Numpy: 1.21.5
Python: 3.7.16
OS: Windows-10-10.0.22000-SP0

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [X] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [X] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

```
# Relevant logs here:
```
Full error - https://pastebin.com/NHisQrCF

## How to reproduce
```
(base)>conda create -y -n sleap -c sleap -c nvidia -c conda-forge sleap=1.3.0
(base)>conda activate sleap
(sleap)>sleap-label
```
See error

**Comment by roomrys** [comment]
Hi @GarrettBlair,

Thanks for reporting this. We just went through a whole episode of updating our dependencies. These packages are still under dev on conda until we officially release them, but if you wouldn't mind being a tester... can you try:
```
conda create -y -n sleap_dev -c sleap/label/dev -c conda-forge -c nvidia -c sleap sleap=1.3.1
```
Followed by the usual
```
conda activate sleap_dev
```

Your error seems to be a conflict between the version of protobuf and tensorflow-hub. My guess would be that protobuf is pulled in by a conda package and then tensorflow-hub is installed via pip and then can't use the version of protobuf that already exists. Anyway, we now list tensorflow-hub as a conda dependency not a pip dependency, so if the above is true, then it shouldn't be a problem anymore.

Thanks,
Liezl

**Comment by GarrettBlair** [comment]
Thanks for the response, I'm happy to help. I installed it with no problems, activated, then ran `sleap-label`, but this time received a different error:

`pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by pynwb`

full error: https://pastebin.com/J6M9EjRS

**Comment by roomrys** [comment]
Hi @GarrettBlair,

I am a bit surprised that during the installation your computer wants to build pynwb instead of using the any one of the none-any wheels (which should work on any operating system and any architecture). One idea is that the tar.gz for pynwb might be in your cache (we want the whl) as it was built from source in a previous environment. We could try removing the environment:
```
conda env remove -n sleap_dev
```
cleaning the cache:
```
conda clean --tarballs
```
and rerunning the install above with a different name after the -n argument (even after removing the environment, occasionally the environment folder is left behind with a few files which should be manually deleted if you want to reuse the same environment name). The hope would be that conda will download the wheel instead of the tarball, but if it doesn't:

We do not have setuptools as a run requirement, but maybe we should if for some reason the user's computer wants to build the packages instead of using the precompiled packages...

Thanks for your help,
Liezl

P.S. Do you mind including which packages are being installed by conda in your next error message (it should be further up).

**Comment by niksirbi** [comment]
I've also had problems with installing sleap v1.3.0 from the conda package.
I suspect my issue may be related to this one (though I can't be sure), that's why I am posting here instead of opening a new issue.


# Bug description

sleap installs without problems using the conda package method, but running command-line programs like `sleap-convert` returns an error.:
```
pkg_resources.DistributionNotFound: The 'wheel~=0.35' distribution was not found and is required by tensorflow
```
For context, this is a server installation on an HPC-cluster without GUI support. Version 1.2.9 (installed on the same cluster but in a separate conda environment) seems to work fine.

## My set up

- OS:
  Ubuntu 20.04
- Version(s):
  Output of `sleap.versions()`:
  SLEAP: 1.3.0
 TensorFlow: 2.6.3
 Numpy: 1.19.5
 Python: 3.7.15
 OS: Linux-5.4.0-109-generic-x86_64-with-debian-bullseye-sid

  Output of `sleap.system_summary()`:
  ```
  GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: None
  ```
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [x] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>


```
# packages in environment at /ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   0.15.0                   pypi_0    pypi
aom                       3.5.0                h27087fc_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
bottleneck                1.3.5            py37hda87dfa_0    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py37h540881e_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.05.30           h06a4308_0  
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.4                    pypi_0    pypi
cairo                     1.16.0            hbbf8b49_1016    conda-forge
cattrs                    1.1.1                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.15.1           py37h43b0acd_1    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
clang                     5.0                      pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
commonmark                0.9.1                    pypi_0    pypi
conda                     23.1.0           py37h06a4308_0  
conda-content-trust       0.1.3              pyhd8ed1ab_0    conda-forge
conda-libmamba-solver     23.1.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.8.0              pyhd8ed1ab_0    conda-forge
cryptography              38.0.2           py37h38fbfac_1    conda-forge
cuda-nvcc                 11.3.58              h2467b9f_0    nvidia
cudatoolkit               11.3.1               ha36c431_9    nvidia
cudnn                     8.2.1.32             h86fa8c9_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
dav1d                     1.2.0                hd590300_0    conda-forge
efficientnet              1.0.0                    pypi_0    pypi
expat                     2.5.0                hcb278e6_1    conda-forge
ffmpeg                    5.1.2           gpl_h9866456_109    conda-forge
flatbuffers               1.12                     pypi_0    pypi
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gast                      0.4.0                    pypi_0    pypi
geos                      3.9.1                h9c3ff4c_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.7.8                hf3e180e_0    conda-forge
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpcio                    1.44.0                   pypi_0    pypi
h5py                      3.1.0           nompi_py37h1e651dc_100    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
hdmf                      3.5.2                    pypi_0    pypi
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.3                      pypi_0    pypi
image-classifiers         1.0.0                    pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
imgstore                  0.2.9                    pypi_0    pypi
importlib-metadata        4.11.1                   pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h0b41bf4_3    conda-forge
jsmin                     3.0.1                    pypi_0    pypi
jsonpickle                1.2                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
keras                     2.6.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.20.1               hf9c8cef_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libarchive                3.6.2                hc8874e4_0    conda-forge
libass                    0.17.1               hc9aadba_0    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libcurl                   8.1.1                h91b91d3_1  
libdeflate                1.10                 h7f98852_0    conda-forge
libdrm                    2.4.114              h166bdaf_0    conda-forge
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.3               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libmamba                  1.3.1                hdb19cb5_0  
libmambapy                1.3.1            py37hdb19cb5_0  
libnghttp2                1.52.0               ha637b67_1  
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.17                 h166bdaf_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsolv                   0.7.24               hfc55251_1    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtasn1                  4.19.0               h166bdaf_0    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libva                     2.18.0               h0b41bf4_0    conda-forge
libvpx                    1.13.0               hcb278e6_0    conda-forge
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.10.4               hfdac1af_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markdown                  3.3.6                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
ncurses                   6.4                  hcb278e6_0    conda-forge
ndx-pose                  0.1.1                    pypi_0    pypi
nettle                    3.8.1                hc379101_1    conda-forge
networkx                  2.6.3                    pypi_0    pypi
nixio                     1.5.3                    pypi_0    pypi
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numexpr                   2.8.3           py37h85a3170_100    conda-forge
numpy                     1.19.5           py37h3e96413_3    conda-forge
oauthlib                  3.2.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.5.5.62                 pypi_0    pypi
opencv-python-headless    4.5.5.62                 pypi_0    pypi
openh264                  2.3.1                hcb278e6_2    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openssl                   1.1.1u               hd590300_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
p11-kit                   0.24.1               hc5aa10d_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5            py37h8c16a72_0  
pcre2                     10.40                hc3806b6_0    conda-forge
pillow                    8.4.0            py37h0f21c89_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
pluggy                    1.0.0            py37h89c1867_3    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4            py37h540881e_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.14.0                   pypi_0    pypi
pykalman                  0.9.5                    pypi_0    pypi
pynwb                     2.3.1                    pypi_0    pypi
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.6                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pyside2                   5.14.1                   pypi_0    pypi
pysocks                   1.7.1            py37h89c1867_5    conda-forge
python                    3.7.15               h7a1cb2a_1  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-rapidjson          1.10                     pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyzmq                     25.0.2                   pypi_0    pypi
qimage2ndarray            1.9.0                    pypi_0    pypi
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      10.16.1                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
ruamel.yaml               0.17.21          py37h540881e_1    conda-forge
ruamel.yaml.clib          0.2.6            py37h540881e_1    conda-forge
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
seaborn                   0.12.2                   pypi_0    pypi
segmentation-models       1.0.1                    pypi_0    pypi
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
setuptools-scm            6.3.2                    pypi_0    pypi
shapely                   1.7.1            py37h48c49eb_5    conda-forge
shiboken2                 5.14.1                   pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sleap                     1.3.0                    pypi_0    pypi
sqlite                    3.42.0               h2c6b66d_0    conda-forge
svt-av1                   1.4.1                hcb278e6_0    conda-forge
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.6.3                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
tensorflow-hub            0.13.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         3.10.0.2                 pypi_0    pypi
typing_extensions         4.6.3              pyha770c72_0    conda-forge
tzdata                    2022.7                   pypi_0    pypi
tzlocal                   4.3                      pypi_0    pypi
urllib3                   1.26.8                   pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.8                h5eee18b_0  
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.18.0           py37h540881e_0    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

</details>

<details><summary>Logs</summary>


```
Traceback (most recent call last):
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
    req, best, replace_conflicting, env, installer, required_by, to_activate
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.19.4 (/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages), Requirement.parse('protobuf>=3.19.6'), {'tensorflow-hub'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/bin/sleap-label", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.0', 'console_scripts', 'sleap-label')())
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/bin/sleap-label", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/sleap/__init__.py", line 10, in <module>
    from sleap.io.dataset import Labels, load_file
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/sleap/io/dataset.py", line 71, in <module>
    from sleap.instance import (
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/sleap/instance.py", line 32, in <module>
    from sleap.io.video import Video
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/sleap/io/video.py", line 17, in <module>
    from sleap.util import json_loads, json_dumps
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/sleap/util.py", line 22, in <module>
    from pkg_resources import Requirement, resource_filename
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 633, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 646, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
    req, best, replace_conflicting, env, installer, required_by, to_activate
  File "/ceph/apps/ubuntu-20/packages/SLEAP/2023-06-15/lib/python3.7/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel~=0.35' distribution was not found and is required by tensorflow
```

</details>

**Comment by GarrettBlair** [comment]
> Hi @GarrettBlair,
> 
> I am a bit surprised that during the installation your computer wants to build pynwb instead of using the any one of the none-any wheels (which should work on any operating system and any architecture). One idea is that the tar.gz for pynwb might be in your cache (we want the whl) as it was built from source in a previous environment. We could try removing the environment:
> 
> ```
> conda env remove -n sleap_dev
> ```
> 
> cleaning the cache:
> 
> ```
> conda clean --tarballs
> ```
> 
> and rerunning the install above with a different name after the -n argument (even after removing the environment, occasionally the environment folder is left behind with a few files which should be manually deleted if you want to reuse the same environment name). The hope would be that conda will download the wheel instead of the tarball, but if it doesn't:
> 
> We do not have setuptools as a run requirement, but maybe we should if for some reason the user's computer wants to build the packages instead of using the precompiled packages...
> 
> Thanks for your help, Liezl
> 
> P.S. Do you mind including which packages are being installed by conda in your next error message (it should be further up).

Here's the full output, including install packages (this time creatively env creatively named sleap_dev2) - https://pastebin.com/krE99B0D. I had just removed the sleap_dev env

Same error, so just cleaning the tarballs wasn't it. I do notice that my conda is a bit outdated, so I could try updating conda?

**Comment by roomrys** [comment]
Hi @GarrettBlair, @niksirbi,

I updated the packages last night. Can you give it a try again? This time, let's be explicit about which build we are pulling in (py37_6):

```
conda create -y -n sleap_dev3 -c conda-forge -c nvidia -c sleap/label/dev -c sleap -c anaconda sleap=1.3.1=py37_6
```

Thanks again!
Liezl

**Comment by GarrettBlair** [comment]
I tried a couple times to install it using:
`conda create -y -n sleap_dev3 -c conda-forge -c nvidia -c sleap/label/dev -c sleap -c anaconda sleap=1.3.1=py37_6`
![image](https://github.com/talmolab/sleap/assets/40305871/18b67f42-e2c5-4ba0-aa69-3e368ff29adb)

but it keeps hanging when trying to solve the environment. `current_repodata.json` fails, and `repodata.json` solves indefinitely (>25 min).

**Comment by roomrys** [comment]
Hi @GarrettBlair,

Yeah, the new dependencies are listed as mostly conda packages, so resolving takes much longer. In the [new installation docs](https://sleap.ai/develop/installation.html#installing-mambaforge) (still in develop - but not for too much longer, especially if we get this installed for you), we migrate over to [Mambaforge](https://mamba.readthedocs.io/en/latest/installation.html) to handle packages resolution since it is MUCH faster.

Thanks for the update,
LIezl

**Comment by GarrettBlair** [comment]
Ah understood, I'll try it again and give it until tomorrow to resolve and will update you then!

-Garrett

**Comment by niksirbi** [comment]
@GarrettBlair I concur, mamba is much much faster at resolving the dependencies.

You don't even need to switch to a full mambaforge installation. You can simply install the `libmamba-solver` in your conda `base` environment, and then use the `--solver=libmamba` option while creating the `sleap_dev3` environment. See [instructions here](https://conda.github.io/conda-libmamba-solver/getting-started/). 



> Hi @GarrettBlair, @niksirbi,
> 
> I updated the packages last night with an updated version constraint on pynwb which [includes this fix](https://github.com/NeurodataWithoutBorders/pynwb/commit/89d9e04b16e8b8241d82384497b741a958a261c4). Can you give it a try again? This time, let's be explicit about which build we are pulling in (py37_6):
> 
> ```
> conda create -y -n sleap_dev3 -c conda-forge -c nvidia -c sleap/label/dev -c sleap -c anaconda sleap=1.3.1=py37_6
> ```
> 
> Thanks again! Liezl

Thanks for the new instructions @roomrys ! I'll give them a try and update you on the outcome.

**Comment by GarrettBlair** [comment]
Hey @roomrys, it did resolve with more time (and thanks @niksirbi for the mamba solver suggestion). Unfortunately I still get the same failue after activate and trying to open the gui with `sleap-label` (full install and error output [here](https://pastebin.com/aKneyx4r))

`pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by pynwb`

**Comment by talmo** [comment]
Hi @GarrettBlair, do you mind trying to `pip install setuptools`? I have a feeling more things will be broken, but worth a quick go. FWIW, we should be getting a full and fixed release out in the next day or so. 🤞

**Comment by GarrettBlair** [comment]
(sleap_dev3) C:\Users\gjb326\Image_Analysis>`pip install setuptools`
Requirement already satisfied: setuptools in c:\users\gjb326\anaconda3\envs\sleap_dev3\lib\site-packages (68.0.0)

Seems like it is installed. And thank you for taking the time to help resolve this!

**Comment by talmo** [comment]
Alright, deactivate that environment and give this another go:

```
mamba create -y -n sleap_dev4 -c conda-forge -c nvidia -c sleap/label/dev -c sleap -c anaconda sleap=1.3.1=py37_7
```

Note the `py37_7` at the end there -- I believe this might contain the fix related to this specific issue as opposed to build `py37_6`.

If you don't have mamba yet, just do `conda install -c conda-forge mamba` and it'll take care of it for you.

Let us know if this works in a new environment with `py37_7` :)

**Comment by GarrettBlair** [comment]
Success! `sleap-label` launched the gui with no issue (and mamba was much faster for the install)
