### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by eringiglio** [talmolab/sleap#1477]
# Bug description

I am doing SLEAP training projects on an enormous dataset, and have been running into a confusing problem with some of my videos: when I try to set up a training job, it throws an error that ends with "overflow error: python int too large to convert to C long." Other similarly sized projects do not throw this bug, but I can't find any obvious corruption within the .slp project. 

## Expected behaviour

I expected to export a training package so I could work on my models remotely.

## Actual behaviour

The training export freezes and this error populates my terminal window. 

## Your personal set up

- OS:
Windows 10 Pro. Will check to see if this is an issue with the same files on my home desktop setup and report back shortly. 
- Version(s):
SLEAP 1.3.0
Python 3.7.12

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ x ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
**pip freeze**
absl-py==0.15.0
astunparse==1.6.3
attrs==21.2.0
backports.zoneinfo==0.2.1
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools==4.2.4
cattrs==1.1.1
certifi==2021.10.8
cffi==1.15.1
charset-normalizer==2.0.12
clang==5.0
colorama==0.4.6
commonmark==0.9.1
cycler==0.11.0
efficientnet==1.0.0
flatbuffers==1.12
fonttools==4.38.0
gast==0.4.0
google-auth==1.35.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.44.0
h5py @ file:///D:/bld/h5py_1604753757907/work
hdmf==3.5.2
idna==3.3
image-classifiers==1.0.0
imageio==2.15.0
imgaug==0.4.0
imgstore==0.2.9
importlib-metadata==4.11.1
importlib-resources==5.12.0
Jinja2==3.1.2
joblib==1.2.0
jsmin==3.0.1
jsonpickle==1.2
jsonschema==4.17.3
keras==2.6.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
Markdown==3.3.6
MarkupSafe==2.1.3
matplotlib==3.5.3
ndx-pose==0.1.1
networkx==2.6.3
nixio==1.5.3
numpy @ file:///D:/bld/numpy_1649281563521/work
oauthlib==3.2.0
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
opencv-python @ git+https://github.com/talmolab/wrap_opencv-python-headless.git@ede49f6a23a73033216339f29515e59d594ba921
opencv-python-headless==4.5.5.62
opt-einsum==3.3.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1673482170163/work
pandas @ file:///D:/bld/pandas_1639398349358/work
patsy==0.5.3
Pillow @ file:///D:/bld/pillow_1636559064986/work
pkgutil_resolve_name==1.3.10
plotly==5.15.0
protobuf==4.22.1
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.14.0
pykalman==0.9.5
pynwb==2.3.1
pyparsing==3.0.7
pyreadline @ file:///D:/bld/pyreadline_1655703530615/work
pyrsistent==0.19.3
PySide2==5.14.1
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-rapidjson==1.10
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.3.0
PyYAML==6.0
pyzmq==25.0.2
qimage2ndarray==1.9.0
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1680148448366/work
requests==2.27.1
requests-oauthlib==1.3.1
rich==10.16.1
rpy2==3.5.13
rsa==4.8
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-image==0.19.3
scikit-learn==1.0.2
scikit-video==1.1.11
scipy @ file:///C:/bld/scipy_1637806996411/work
seaborn==0.12.2
segmentation-models==1.0.1
setuptools-scm==6.4.2
Shapely==1.7.1
shiboken2==5.14.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
sleap==1.3.0
statsmodels==0.13.5
tenacity==8.2.2
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.6.3
tensorflow-estimator==2.6.0
tensorflow-hub==0.13.0
termcolor==1.1.0
threadpoolctl==3.1.0
tifffile==2021.11.2
tomli==2.0.1
typing-extensions==3.10.0.2
tzdata==2022.7
tzlocal==4.3
urllib3==1.26.8
Werkzeug==2.0.3
wrapt==1.12.1
zipp==3.7.0

**conda list**
# packages in environment at C:\Users\ering\anaconda3\envs\sleap_v2:
#
# Name                    Version                   Build  Channel
absl-py                   0.15.0                   pypi_0    pypi
aom                       3.5.0                h63175ca_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.4                    pypi_0    pypi
cattrs                    1.1.1                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
clang                     5.0                      pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cuda-nvcc                 11.3.58              hb8d16a4_0    nvidia
cudatoolkit               11.3.1              hf2f0253_11    conda-forge
cudnn                     8.2.1.32             h754d62a_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
efficientnet              1.0.0                    pypi_0    pypi
expat                     2.5.0                h63175ca_1    conda-forge
ffmpeg                    5.1.2           gpl_h5b1d025_106    conda-forge
flatbuffers               1.12                     pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h546665d_1    conda-forge
gast                      0.4.0                    pypi_0    pypi
geos                      3.9.1                h39d44d4_2    conda-forge
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.44.0                   pypi_0    pypi
h5py                      3.1.0           nompi_py37h19fda09_100    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
hdmf                      3.5.2                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
image-classifiers         1.0.0                    pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
imgstore                  0.2.9                    pypi_0    pypi
importlib-metadata        4.11.1                   pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   hcfcfb64_3    conda-forge
jsmin                     3.0.1                    pypi_0    pypi
jsonpickle                1.2                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
keras                     2.6.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libhwloc                  2.9.0                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libtiff                   4.3.0                hc4061b1_4    conda-forge
libxml2                   2.10.3               hc3477c8_6    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.6                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
ndx-pose                  0.1.1                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
nixio                     1.5.3                    pypi_0    pypi
numpy                     1.19.5           py37h4c2b6ed_3    conda-forge
oauthlib                  3.2.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.5.5.62                 pypi_0    pypi
opencv-python-headless    4.5.5.62                 pypi_0    pypi
openh264                  2.3.1                h63175ca_2    conda-forge
openjpeg                  2.5.0                hb211442_0    conda-forge
openssl                   3.1.0                hcfcfb64_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5            py37h9386db6_0    conda-forge
patsy                     0.5.3                    pypi_0    pypi
pillow                    8.4.0            py37hd7d9ad0_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
plotly                    5.15.0                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pykalman                  0.9.5                    pypi_0    pypi
pynwb                     2.3.1                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
pyreadline                2.1             py37h03978a9_1006    conda-forge
pyrsistent                0.19.3                   pypi_0    pypi
pyside2                   5.14.1                   pypi_0    pypi
python                    3.7.12          h900ac77_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-rapidjson          1.10                     pypi_0    pypi
python_abi                3.7                     3_cp37m    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyzmq                     25.0.2                   pypi_0    pypi
qimage2ndarray            1.9.0                    pypi_0    pypi
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      10.16.1                  pypi_0    pypi
rpy2                      3.5.13                   pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.7.3            py37hb6553fb_0    conda-forge
seaborn                   0.12.2                   pypi_0    pypi
segmentation-models       1.0.1                    pypi_0    pypi
setuptools                59.8.0           py37h03978a9_1    conda-forge
setuptools-scm            6.4.2                    pypi_0    pypi
shapely                   1.7.1            py37hc520ffa_5    conda-forge
shiboken2                 5.14.1                   pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sleap                     1.3.0                    pypi_0    pypi
sqlite                    3.40.0               hcfcfb64_0    conda-forge
statsmodels               0.13.5                   pypi_0    pypi
svt-av1                   1.4.1                h63175ca_0    conda-forge
tbb                       2021.8.0             h91493d7_0    conda-forge
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.6.3                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
tensorflow-hub            0.13.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
typing-extensions         3.10.0.2                 pypi_0    pypi
tzdata                    2022.7                   pypi_0    pypi
tzlocal                   4.3                      pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge

```

</details>

<details><summary>Logs</summary>

Here is a sample of the error output from my command window: 

> Traceback (most recent call last):
>   File "C:\Users\ering\anaconda3\envs\sleap_v2\lib\site-packages\sleap\gui\learning\dialog.py", line 788, in export_package
>     suggested=include_suggestions,
>   File "C:\Users\ering\anaconda3\envs\sleap_v2\lib\site-packages\sleap\gui\commands.py", line 1401, in export_dataset_gui
>     progress_callback=update_progress,
>   File "C:\Users\ering\anaconda3\envs\sleap_v2\lib\site-packages\sleap\io\dataset.py", line 1994, in save_file
>     write(filename, labels, *args, **kwargs)
>   File "C:\Users\ering\anaconda3\envs\sleap_v2\lib\site-packages\sleap\io\format\main.py", line 162, in write
>     return disp.write(filename, source_object, *args, **kwargs)
>   File "C:\Users\ering\anaconda3\envs\sleap_v2\lib\site-packages\sleap\io\format\dispatch.py", line 78, in write
>     return adaptor.write(filename, source_object, *args, **kwargs)
>   File "C:\Users\ering\anaconda3\envs\sleap_v2\lib\site-packages\sleap\io\format\hdf5.py", line 253, in write
>     progress_callback=progress_callback,
>   File "C:\Users\ering\anaconda3\envs\sleap_v2\lib\site-packages\sleap\io\dataset.py", line 2331, in save_frame_data_hdf5
>     frame_numbers=frame_nums,
>   File "C:\Users\ering\anaconda3\envs\sleap_v2\lib\site-packages\sleap\io\video.py", line 1418, in to_hdf5
>     frame_numbers_data = np.array(list(frame_numbers), dtype=int)
> OverflowError: Python int too large to convert to C long
```
# paste relevant logs here, if any
```

</details>

## How to reproduce

Go to "Run Training"
make selections for a training file
export training package

**Comment by roomrys** [comment]
Stemming from the discussion in [this post](https://stackoverflow.com/a/38314163/13281260), it seems that one of the `frame_numbers > sys.maxsize`. I did a few short tests and one possible solution is that we could use an unsigned integer to expand the allowable range:
```python
In [27]: frame_numbers = [sys.maxsize]

In [28]: frame_numbers_data = np.array(frame_numbers, dtype=int)

In [29]: frame_numbers = [sys.maxsize + 1]

In [30]: frame_numbers_data = np.array(frame_numbers, dtype=int)
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-30-a981235bf25b> in <module>
----> 1 frame_numbers_data = np.array(frame_numbers, dtype=int)

OverflowError: Python int too large to convert to C long

In [31]: frame_numbers_data = np.array(frame_numbers, dtype=np.uint64)

In [32]: frame_numbers_data
Out[32]: array([9223372036854775808], dtype=uint64)

In [33]: sys.maxsize + 1
Out[33]: 9223372036854775808
```

**Comment by talmo** [comment]
Hi @eringiglio,

Can you do us a favor a help us with collecting some diagnostic information? Do you mind sending us the result of running this command:

```
python -c "import sleap; labels = sleap.load_file("labels.v001.slp"); print([v.shape for v in labels.videos])"
```

Just make sure to replace `labels.v001.slp` above with your labels filename.

Thanks!!

Talmo

**Comment by eringiglio** [comment]
Absolutely I can do that! Here's the result: 

> [(163285, 1080, 1920, 3), (163913, 1080, 1920, 3), (163907, 1080, 1920, 3), (166655, 1080, 1920, 3), (183395, 1080, 1920, 3), (167758, 1080, 1920, 3), (163372, 1080, 1920, 3), (157149, 1080, 1920, 3), (166493, 1080, 1920, 3), (164176, 1080, 1920, 3), (165402, 1080, 1920, 3), (163397, 1080, 1920, 3), (167283, 1080, 1920, 3), (166695, 1080, 1920, 3), (162545, 1080, 1920, 3), (164339, 1080, 1920, 3), (165396, 1080, 1920, 3), (165013, 1080, 1920, 3), (177270, 1080, 1920, 3), (163887, 1080, 1920, 3), (166201, 1080, 1920, 3), (164832, 1080, 1920, 3), (167145, 1080, 1920, 3), (165411, 1080, 1920, 3), (162738, 1080, 1920, 3), (161845, 1080, 1920, 3), (161849, 1080, 1920, 3), (161844, 1080, 1920, 3), (161897, 1080, 1920, 3), (161845, 1080, 1920, 3), (161864, 1080, 1920, 3), (161841, 1080, 1920, 3), (161839, 1080, 1920, 3)]

**Comment by eringiglio** [comment]
oh, I just checked sys.maxsize as well in python: sys.maxsize = 9223372036854775807. So I don't think it's the number of frames in the video. I wonder... hold on, let me check on the suggested frames, see if it's in there somewhere.

**Comment by eringiglio** [comment]
aha. think I have it. It's in the labeled frames for some reason, I think... anyway, here's what I have plus outputs. (NB: the mouse is named donut1; I'm not putting in the full path to the file but you get the idea.) 

`
> filename='donut1.slp' 
> labels = sleap.Labels.load_file(filename)
> badLabels = [x for x in labels.labeled_frames if x.frame_idx > 180000]
> badLabels
[LabeledFrame(video=MediaVideo('donut1_drug2.12.MP4'), frame_idx=182139, instances=1), LabeledFrame(video=MediaVideo('donut1_drug2.12.MP4'), frame_idx=181475, instances=1), LabeledFrame(video=MediaVideo('donut1_drug2.12.MP4'), frame_idx=181925, instances=1), LabeledFrame(video=MediaVideo('donut1_drug2.12.MP4'), frame_idx=181902, instances=1), LabeledFrame(video=MediaVideo('donut1_drug2.12.MP4'), frame_idx=180198, 
instances=1), LabeledFrame(video=MediaVideo('donut1_drug3.2.MP4'), frame_idx=18446744073709551592, instances=1), LabeledFrame(video=MediaVideo('donut1_drug3.4.MP4'), frame_idx=18446744073709551592, instances=1), LabeledFrame(video=MediaVideo('donut1_drug3.4.MP4'), frame_idx=18446744073709551592, instances=1), LabeledFrame(video=MediaVideo('donut1_drug3.4.MP4'), frame_idx=18446744073709551592, instances=1)]     `

The video donut1_drug2.12.MP4 is unusually long and does actually have slightly more than 180000 frames, so that's reasonable enough. But these other frames--the last four--I bet you those are my problem. I'll purge them from the file and see if that fixes the issue. I am slightly embarrassed it's taken me this long to bother looking at sys.maxsize to get a feel for _how_ wildly off some of this stuff is!

**Comment by eringiglio** [comment]
Definitely fixed the issue. Thanks!
