### ISSUE TITLE
UnicodeDecodeError when trying command-line sleap-track

### ISSUE THREAD

**Issue by ohmstead** [talmolab/sleap#1478]
# Bug description

I have many videos distributed across different animal/session folders that I'd like to track. I wrote a python script to use SLEAP command-line tools to perform this function.

I ran the following command from my SLEAP mamba environment:

> sleap-track -m "C:\\Users\\User\\Dropbox\\data\\ephys\\sleap\\models\\230811_110459.single_instance.n=117\\training_config.json" -m "C:\\Users\\User\\Dropbox\\data\\ephys\\sleap\\models\\230811_110459.single_instance.n=117\\best_model.h5" -o "E:\\AP30\\AP3020190130\\Track\\AP30_20190130_ffmpeg_Track.predictions.slp" "E:\\AP30\\AP3020190130\\Track\\AP30_20190130_ffmpeg_Track.mp4"

## Expected behaviour

I thought it would track the video and produce a .slp predictions file in the folder.

## Actual behaviour

I get the following terminal output:

(sleap) C:\WINDOWS\system32>sleap-track -m "C:/Users/User/Documents/sleap/models/230811_110459.single_instance.n=117/best_model.h5" -m "C:/Users/User/Documents/sleap/models/230811_110459.single_instance.n=117/training_config.json" -o "E:/AP30/AP3020190130/Track/AP30_20190130_ffmpeg_Track.predictions.slp" "E:/AP30/AP3020190130/Track/AP30_20190130_ffmpeg_Track.mp4"
Started inference at: 2023-09-06 18:35:28.573115
Args:
{
│   'data_path': 'E:/AP30/AP3020190130/Track/AP30_20190130_ffmpeg_Track.mp4',
│   'models': [
│   │   'C:/Users/User/Documents/sleap/models/230811_110459.single_instance.n=117/best_model.h5',
│   │   'C:/Users/User/Documents/sleap/models/230811_110459.single_instance.n=117/training_config.json'
│   ],
│   'frames': '',
│   'only_labeled_frames': False,
│   'only_suggested_frames': False,
│   'output': 'E:/AP30/AP3020190130/Track/AP30_20190130_ffmpeg_Track.predictions.slp',
│   'no_empty_frames': False,
│   'verbosity': 'rich',
│   'video.dataset': None,
│   'video.input_format': 'channels_last',
│   'video.index': '',
│   'cpu': False,
│   'first_gpu': False,
│   'last_gpu': False,
│   'gpu': 'auto',
│   'max_edge_length_ratio': 0.25,
│   'dist_penalty_weight': 1.0,
│   'batch_size': 4,
│   'open_in_gui': False,
│   'peak_threshold': 0.2,
│   'max_instances': None,
│   'tracking.tracker': None,
│   'tracking.target_instance_count': None,
│   'tracking.pre_cull_to_target': None,
│   'tracking.pre_cull_iou_threshold': None,
│   'tracking.post_connect_single_breaks': None,
│   'tracking.clean_instance_count': None,
│   'tracking.clean_iou_threshold': None,
│   'tracking.similarity': None,
│   'tracking.match': None,
│   'tracking.robust': None,
│   'tracking.track_window': None,
│   'tracking.min_new_track_points': None,
│   'tracking.min_match_points': None,
│   'tracking.img_scale': None,
│   'tracking.of_window_size': None,
│   'tracking.of_max_levels': None,
│   'tracking.save_shifted_instances': None,
│   'tracking.kf_node_indices': None,
│   'tracking.kf_init_frame_count': None
}

INFO:sleap.nn.inference:Auto-selected GPU 0 with 11014 MiB of free memory.
Versions:
SLEAP: 1.3.1
TensorFlow: 2.7.0
Numpy: 1.21.6
Python: 3.7.12
OS: Windows-10-10.0.19041-SP0

System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True

Video: E:/AP30/AP3020190130/Track/AP30_20190130_ffmpeg_Track.mp4
Traceback (most recent call last):
  File "C:\mambaforge\envs\sleap\Scripts\sleap-track-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.1', 'console_scripts', 'sleap-track')())
  File "C:\mambaforge\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 5408, in main
    predictor = _make_predictor_from_cli(args)
  File "C:\mambaforge\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 5306, in _make_predictor_from_cli
    max_instances=args.max_instances,
  File "C:\mambaforge\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 4856, in load_model
    max_instances=max_instances,
  File "C:\mambaforge\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 227, in from_model_paths
    model_configs = [sleap.load_config(model_path) for model_path in model_paths]
  File "C:\mambaforge\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 227, in <listcomp>
    model_configs = [sleap.load_config(model_path) for model_path in model_paths]
  File "C:\mambaforge\envs\sleap\lib\site-packages\sleap\nn\config\training_job.py", line 158, in load_config
    filename, load_training_config=load_training_config
  File "C:\mambaforge\envs\sleap\lib\site-packages\sleap\nn\config\training_job.py", line 120, in load_json
    json_data = f.read()
  File "C:\mambaforge\envs\sleap\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1376: character maps to <undefined>

## Your personal set up

I am using a windows computer, running SLEAP from the anaconda prompt opened as administrator. I installed SLEAP using mamba according to the recommended install method.

- OS: Windows 10 64-bit
- Version(s): SLEAP v1.3.1, python 3.7.12

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
Mamba

<details><summary>Environment packages</summary>

```
# packages in environment at C:\mambaforge\envs\sleap:
#
# Name                    Version                   Build  Channel
absl-py                   1.0.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backports-zoneinfo        0.2.1                    pypi_0    pypi
brotli                    1.0.9                hcfcfb64_9    conda-forge
brotli-bin                1.0.9                hcfcfb64_9    conda-forge
ca-certificates           2023.05.30           haa95532_0
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.4                    pypi_0    pypi
cattrs                    1.1.1              pyhd8ed1ab_0    conda-forge
certifi                   2020.6.20          pyhd3eb1b0_3
charset-normalizer        2.0.9                    pypi_0    pypi
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
cuda-nvcc                 11.3.58              hb8d16a4_0    nvidia
cudatoolkit               11.3.1              hf2f0253_12    conda-forge
cudnn                     8.2.1.32             h754d62a_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py37hcc03f2d_0    conda-forge
dask-core                 2022.2.0           pyhd8ed1ab_0    conda-forge
efficientnet              1.0.0                    pypi_0    pypi
ffmpeg                    4.2.2                he774522_0
flatbuffers               2.0                      pypi_0    pypi
fonttools                 4.38.0           py37h51bd9d9_0    conda-forge
freeglut                  3.2.2                h63175ca_2    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
fsspec                    2023.1.0           pyhd8ed1ab_0    conda-forge
gast                      0.4.0                    pypi_0    pypi
geos                      3.11.0               h39d44d4_0    conda-forge
google-auth               2.3.3                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdmf                      3.6.1                    pypi_0    pypi
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.3                      pypi_0    pypi
image-classifiers         1.0.0                    pypi_0    pypi
imagecodecs-lite          2019.12.3        py37h0b711f8_5    conda-forge
imageio                   2.31.1             pyh24c5eb1_0    conda-forge
imgaug                    0.4.0              pyhd8ed1ab_1    conda-forge
imgstore                  0.2.9                    pypi_0    pypi
importlib-metadata        4.2.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.2.0         h57928b3_49496    conda-forge
jasper                    2.0.33               hc2e4405_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
jsmin                     3.0.1              pyhd8ed1ab_0    conda-forge
jsonpickle                1.2                        py_0    conda-forge
jsonschema                4.17.3                   pypi_0    pypi
keras                     2.7.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4            py37h8c56517_0    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              17_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_9    conda-forge
libbrotlidec              1.0.9                hcfcfb64_9    conda-forge
libbrotlienc              1.0.9                hcfcfb64_9    conda-forge
libcblas                  3.9.0              17_win64_mkl    conda-forge
libclang                  12.0.0                   pypi_0    pypi
libdeflate                1.14                 hcfcfb64_0    conda-forge
libhwloc                  2.9.2           nocuda_h15da153_1008    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              17_win64_mkl    conda-forge
liblapacke                3.9.0              17_win64_mkl    conda-forge
libopencv                 4.5.5           py37h542666b_10    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libprotobuf               3.20.3               h12be248_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libtiff                   4.4.0                hc4f729c_5    conda-forge
libwebp-base              1.3.1                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.11.5               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.6                    pypi_0    pypi
markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
matplotlib-base           3.5.3            py37hbaab90a_2    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ndx-pose                  0.1.1                    pypi_0    pypi
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nixio                     1.5.3                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
opencv                    4.5.5           py37h03978a9_10    conda-forge
opencv-python-headless    4.2.0.34                 pypi_0    pypi
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   1.1.1v               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5            py37h9386db6_0    conda-forge
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pillow                    9.2.0            py37h42a8222_2    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
protobuf                  3.19.1                   pypi_0    pypi
psutil                    5.9.3            py37h51bd9d9_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py-opencv                 4.5.5           py37h90c5f73_10    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pykalman                  0.9.5                      py_1    conda-forge
pynwb                     2.3.3                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pyside2                   5.13.1           py37hd7ce7fb_3    conda-forge
python                    3.7.12          h7840368_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-rapidjson          1.9              py37h7f67f24_0    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py37h3a130e4_1    conda-forge
pyyaml                    6.0              py37hcc03f2d_4    conda-forge
pyzmq                     24.0.1           py37h7347f05_0    conda-forge
qimage2ndarray            1.10.0                   pypi_0    pypi
qt                        5.12.9               h556501e_6    conda-forge
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rich                      13.5.1             pyhd8ed1ab_0    conda-forge
ruamel-yaml               0.17.32                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-image              0.19.3           py37h3182a2c_1    conda-forge
scikit-learn              1.0              py37ha78be43_1    conda-forge
scikit-video              1.1.11             pyh24bf2e0_0    conda-forge
scipy                     1.7.3            py37hb6553fb_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
segmentation-models       1.0.1                    pypi_0    pypi
setuptools                59.8.0           py37h03978a9_1    conda-forge
setuptools-scm            6.3.2                    pypi_0    pypi
shapely                   1.8.5            py37h475e9a0_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleap                     1.3.1                    pypi_0    pypi
sqlite                    3.42.0               hcfcfb64_0    conda-forge
statsmodels               0.13.2           py37h3a130e4_0    conda-forge
tbb                       2021.10.0            h91493d7_0    conda-forge
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.7.0                    pypi_0    pypi
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-hub            0.12.0             pyhca92ed8_0    conda-forge
tensorflow-io-gcs-filesystem 0.23.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2020.6.3                   py_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.0                    pypi_0    pypi
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.0.1                    pypi_0    pypi
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
tzlocal                   5.0.1                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py37hcc03f2d_1    conda-forge
urllib3                   1.26.7                   pypi_0    pypi
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.13.3                   pypi_0    pypi
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.15.0                   pypi_0    pypi
zstd                      1.5.2                h12be248_7    conda-forge```

</details>

<details><summary>Logs</summary>
<!--
Please share any applicable terminal logs. optionally share output from sleap-diagnostic
-->

```
# paste relevant logs here, if any
```

</details>

## Screenshots

<!-- Provide any relevant screenshots -->

## How to reproduce

<!-- Use this section to describe the steps that a user would take to experience this bug. eg:-->

1. activate SLEAP environment
2. run sleap-track, pointing to a model's training_config.json and best_model.h5

**Comment by ohmstead** [comment]
Found the issue! I made a silly mistake: I was pointing to the model's config and structure when calling `sleap-track`, rather than just pointing to the model folder. I was a little confused in the documentation, because it talks about both the training_config.json and .h5 structure file, so I thought these needed to be -m arguments. Anyway, the following code is working now:

`sleap-track "E:\AP30\AP3020190130\Track\AP30_20190130_ffmpeg_Track.mp4" -m "C:\Users\User\Dropbox\data\ephys\sleap\models\230811_110459.single_instance.n=117\ -o "E:\AP30\AP3020190130\Track\AP30_20190130_ffmpeg_Track.predictions.slp"`

**Comment by talmo** [comment]
Thanks for the report back @ohmstead!

I think we can handle this programmatically so that you can flexibly provide the path to either the folder OR the checkpoint since the file structure is pretty standardized.

Closing this issue but we opened #1480 to track this enhancement.

Cheers,

Talmo
