### ISSUE TITLE
--tracking.tracker simplemaxtracks invalid parameter

### ISSUE THREAD

**Issue by mollywestbrook** [talmolab/sleap#1571]
# Bug description

Using a university computer cluster to remotely track and wrote a slurm script (based on the script referenced in #1555). Tracking parameters were set to `--tracking.tracker simplemaxtracks --tracking.max_tracking 1 --tracking.max_tracks 5 --tracking.post_connect_single_breaks 1`. When I ran the script, I received the following error: 

`Traceback (most recent call last):
  File "/home/mwestbr2/mambaforge/envs/sleap/bin/sleap-track", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.1', 'console_scripts', 'sleap-track')())
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5400, in main
    tracker = _make_tracker_from_cli(args)
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5334, in _make_tracker_from_cli
    tracker = Tracker.make_tracker_by_name(**policy_args["tracking"])
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/tracking.py", line 634, in make_tracker_by_name
    raise ValueError(f"{tracker} is not a valid tracker.")
ValueError: simplemaxtracks is not a valid tracker.` 

## Expected behaviour

According to docs, simplemaxtracks is a parameter listed under --tracking.tracker.

## Actual behaviour

When I ran the script, simplemaxtracks was not considered a valid parameter.

## Your personal set up

Our compute cluster uses AMD 7763 64-core CPUs and  Nvidia A100 GPUs

The full script I am using to batch track videos on the cluster:

```
#!/bin/bash
#SBATCH -t 30:0:0
#SBATCH -n 1
#SBATCH -p gpu
#SBATCH --gres=gpu:2
#SBATCH --mem=120gb
#SBATCH --mail-user=mwestbr2@umd.edu
#SBATCH --mail-type=ALL

eval "$(conda shell.bash hook)"
conda activate sleap
cd /scratch/zt1/project/juntti-lab/shared/sleap

#define the path to the SLEAP executable and model paths
sleap_executable="sleap-track"
model_paths="-m /scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centered_instance/training_config.json -m /scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centroid/training_config.json"

#define tracking parameters
tracking_params="--tracking.tracker simplemaxtracks --tracking.max_tracking 1 --tracking.max_tracks 5 --tracking.post_connect_single_breaks 1"

#get the list of video files in folder
video_folder="/scratch/zt1/project/juntti-lab/shared/sleap/videos"
video_files=$(ls "$video_folder")

#iterate through the video files and run SLEAP commands
for video_file in $video_files; do
    if [[ $video_file == *.mp4 ]]; then
        input_video_path="$video_folder/$video_file"
        output_sleap_path="/scratch/zt1/project/juntti-lab/shared/sleap/predictions/predictions_$video_file.slp"
        command="$sleap_executable $input_video_path $tracking_params -o $output_sleap_path $$model_paths"
        echo "Processing $input_video_path..."
        $command
    fi
done
```

Sleap was installed on the cluster via miniconda create. 

conda list output:

```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotli-python             1.0.9           py310hd8f1fbe_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.1.0          py310hff52083_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.8.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.2          py310h75e40e8_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.1               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libcurl                   8.1.2                hca28451_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmamba                  1.4.2                hcea66bb_0    conda-forge
libmambapy                1.4.2           py310h1428755_0    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.24               hfc55251_1    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.4.2           py310h51d5547_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h5764c6d_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.12         hd12c33a_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.32         py310h2372a71_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h1fa729e_1    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zstandard                 0.19.0          py310h1275a96_2    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
````

And the full slurm output for reference:

```
WARNING: overwriting environment variables set in the machine
overwriting variable {'LD_PRELOAD'}
Processing /scratch/zt1/project/juntti-lab/shared/sleap/videos/03-08-2023_group1_R.mp4...
Started inference at: 2023-10-24 15:06:19.460656
Args:
{
│   'data_path': '/scratch/zt1/project/juntti-lab/shared/sleap/videos/03-08-2023_group1_R.mp4',
│   'models': [
│   │   '/scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centered_instance/training_config.json',
│   │   '/scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centroid/training_config.json'
│   ],
│   'frames': '',
│   'only_labeled_frames': False,
│   'only_suggested_frames': False,
│   'output': '/scratch/zt1/project/juntti-lab/shared/sleap/predictions/predictions_03-08-2023_group1_R.mp4.slp',
│   'no_empty_frames': False,
│   'verbosity': 'rich',
│   'video.dataset': None,
│   'video.input_format': 'channels_last',
│   'video.index': '',
│   'cpu': False,
│   'first_gpu': False,
│   'last_gpu': False,
│   'gpu': 'auto',
│   'max_edge_length_ratio': 0.25,
│   'dist_penalty_weight': 1.0,
│   'batch_size': 4,
│   'open_in_gui': False,
│   'peak_threshold': 0.2,
│   'max_instances': None,
│   'tracking.tracker': 'simplemaxtracks',
│   'tracking.target_instance_count': None,
│   'tracking.pre_cull_to_target': None,
│   'tracking.pre_cull_iou_threshold': None,
│   'tracking.post_connect_single_breaks': 1,
│   'tracking.clean_instance_count': None,
│   'tracking.clean_iou_threshold': None,
│   'tracking.similarity': None,
│   'tracking.match': None,
│   'tracking.robust': None,
│   'tracking.track_window': None,
│   'tracking.min_new_track_points': None,
│   'tracking.min_match_points': None,
│   'tracking.img_scale': None,
│   'tracking.of_window_size': None,
│   'tracking.of_max_levels': None,
│   'tracking.save_shifted_instances': None,
│   'tracking.kf_node_indices': None,
│   'tracking.kf_init_frame_count': None
}

INFO:sleap.nn.inference:Auto-selected GPU 0 with 40373 MiB of free memory.
Versions:
SLEAP: 1.3.1
TensorFlow: 2.7.0
Numpy: 1.19.5
Python: 3.7.12
OS: Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-redhat-8.7-Ootpa

System:
GPUs: 1/2 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
  Device: /physical_device:GPU:1
         Available: False
        Initalized: False
     Memory growth: None

Video: /scratch/zt1/project/juntti-lab/shared/sleap/videos/03-08-2023_group1_R.mp4
Traceback (most recent call last):
  File "/home/mwestbr2/mambaforge/envs/sleap/bin/sleap-track", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.1', 'console_scripts', 'sleap-track')())
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5400, in main
    tracker = _make_tracker_from_cli(args)
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5334, in _make_tracker_from_cli
    tracker = Tracker.make_tracker_by_name(**policy_args["tracking"])
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/tracking.py", line 634, in make_tracker_by_name
    raise ValueError(f"{tracker} is not a valid tracker.")
ValueError: simplemaxtracks is not a valid tracker.
Processing /scratch/zt1/project/juntti-lab/shared/sleap/videos/04-08-2023_group3_R.mp4...
Started inference at: 2023-10-24 15:06:24.940324
Args:
{
│   'data_path': '/scratch/zt1/project/juntti-lab/shared/sleap/videos/04-08-2023_group3_R.mp4',
│   'models': [
│   │   '/scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centered_instance/training_config.json',
│   │   '/scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centroid/training_config.json'
│   ],
│   'frames': '',
│   'only_labeled_frames': False,
│   'only_suggested_frames': False,
│   'output': '/scratch/zt1/project/juntti-lab/shared/sleap/predictions/predictions_04-08-2023_group3_R.mp4.slp',
│   'no_empty_frames': False,
│   'verbosity': 'rich',
│   'video.dataset': None,
│   'video.input_format': 'channels_last',
│   'video.index': '',
│   'cpu': False,
│   'first_gpu': False,
│   'last_gpu': False,
│   'gpu': 'auto',
│   'max_edge_length_ratio': 0.25,
│   'dist_penalty_weight': 1.0,
│   'batch_size': 4,
│   'open_in_gui': False,
│   'peak_threshold': 0.2,
│   'max_instances': None,
│   'tracking.tracker': 'simplemaxtracks',
│   'tracking.target_instance_count': None,
│   'tracking.pre_cull_to_target': None,
│   'tracking.pre_cull_iou_threshold': None,
│   'tracking.post_connect_single_breaks': 1,
│   'tracking.clean_instance_count': None,
│   'tracking.clean_iou_threshold': None,
│   'tracking.similarity': None,
│   'tracking.match': None,
│   'tracking.robust': None,
│   'tracking.track_window': None,
│   'tracking.min_new_track_points': None,
│   'tracking.min_match_points': None,
│   'tracking.img_scale': None,
│   'tracking.of_window_size': None,
│   'tracking.of_max_levels': None,
│   'tracking.save_shifted_instances': None,
│   'tracking.kf_node_indices': None,
│   'tracking.kf_init_frame_count': None
}

INFO:sleap.nn.inference:Auto-selected GPU 0 with 40373 MiB of free memory.
Versions:
SLEAP: 1.3.1
TensorFlow: 2.7.0
Numpy: 1.19.5
Python: 3.7.12
OS: Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-redhat-8.7-Ootpa

System:
GPUs: 1/2 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
  Device: /physical_device:GPU:1
         Available: False
        Initalized: False
     Memory growth: None

Video: /scratch/zt1/project/juntti-lab/shared/sleap/videos/04-08-2023_group3_R.mp4
Traceback (most recent call last):
  File "/home/mwestbr2/mambaforge/envs/sleap/bin/sleap-track", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.1', 'console_scripts', 'sleap-track')())
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5400, in main
    tracker = _make_tracker_from_cli(args)
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5334, in _make_tracker_from_cli
    tracker = Tracker.make_tracker_by_name(**policy_args["tracking"])
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/tracking.py", line 634, in make_tracker_by_name
    raise ValueError(f"{tracker} is not a valid tracker.")
ValueError: simplemaxtracks is not a valid tracker.
Processing /scratch/zt1/project/juntti-lab/shared/sleap/videos/08-02-2023_piz3_T6.mp4...
Started inference at: 2023-10-24 15:06:29.226010
Args:
{
│   'data_path': '/scratch/zt1/project/juntti-lab/shared/sleap/videos/08-02-2023_piz3_T6.mp4',
│   'models': [
│   │   '/scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centered_instance/training_config.json',
│   │   '/scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centroid/training_config.json'
│   ],
│   'frames': '',
│   'only_labeled_frames': False,
│   'only_suggested_frames': False,
│   'output': '/scratch/zt1/project/juntti-lab/shared/sleap/predictions/predictions_08-02-2023_piz3_T6.mp4.slp',
│   'no_empty_frames': False,
│   'verbosity': 'rich',
│   'video.dataset': None,
│   'video.input_format': 'channels_last',
│   'video.index': '',
│   'cpu': False,
│   'first_gpu': False,
│   'last_gpu': False,
│   'gpu': 'auto',
│   'max_edge_length_ratio': 0.25,
│   'dist_penalty_weight': 1.0,
│   'batch_size': 4,
│   'open_in_gui': False,
│   'peak_threshold': 0.2,
│   'max_instances': None,
│   'tracking.tracker': 'simplemaxtracks',
│   'tracking.target_instance_count': None,
│   'tracking.pre_cull_to_target': None,
│   'tracking.pre_cull_iou_threshold': None,
│   'tracking.post_connect_single_breaks': 1,
│   'tracking.clean_instance_count': None,
│   'tracking.clean_iou_threshold': None,
│   'tracking.similarity': None,
│   'tracking.match': None,
│   'tracking.robust': None,
│   'tracking.track_window': None,
│   'tracking.min_new_track_points': None,
│   'tracking.min_match_points': None,
│   'tracking.img_scale': None,
│   'tracking.of_window_size': None,
│   'tracking.of_max_levels': None,
│   'tracking.save_shifted_instances': None,
│   'tracking.kf_node_indices': None,
│   'tracking.kf_init_frame_count': None
}

INFO:sleap.nn.inference:Auto-selected GPU 0 with 40373 MiB of free memory.
Versions:
SLEAP: 1.3.1
TensorFlow: 2.7.0
Numpy: 1.19.5
Python: 3.7.12
OS: Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-redhat-8.7-Ootpa

System:
GPUs: 1/2 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
  Device: /physical_device:GPU:1
         Available: False
        Initalized: False
     Memory growth: None

Video: /scratch/zt1/project/juntti-lab/shared/sleap/videos/08-02-2023_piz3_T6.mp4
Traceback (most recent call last):
  File "/home/mwestbr2/mambaforge/envs/sleap/bin/sleap-track", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.1', 'console_scripts', 'sleap-track')())
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5400, in main
    tracker = _make_tracker_from_cli(args)
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5334, in _make_tracker_from_cli
    tracker = Tracker.make_tracker_by_name(**policy_args["tracking"])
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/tracking.py", line 634, in make_tracker_by_name
    raise ValueError(f"{tracker} is not a valid tracker.")
ValueError: simplemaxtracks is not a valid tracker.
Processing /scratch/zt1/project/juntti-lab/shared/sleap/videos/08-07-2023_piz3_T6.mp4...
Started inference at: 2023-10-24 15:06:33.978434
Args:
{
│   'data_path': '/scratch/zt1/project/juntti-lab/shared/sleap/videos/08-07-2023_piz3_T6.mp4',
│   'models': [
│   │   '/scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centered_instance/training_config.json',
│   │   '/scratch/zt1/project/juntti-lab/shared/sleap/models/230929_171643.centroid/training_config.json'
│   ],
│   'frames': '',
│   'only_labeled_frames': False,
│   'only_suggested_frames': False,
│   'output': '/scratch/zt1/project/juntti-lab/shared/sleap/predictions/predictions_08-07-2023_piz3_T6.mp4.slp',
│   'no_empty_frames': False,
│   'verbosity': 'rich',
│   'video.dataset': None,
│   'video.input_format': 'channels_last',
│   'video.index': '',
│   'cpu': False,
│   'first_gpu': False,
│   'last_gpu': False,
│   'gpu': 'auto',
│   'max_edge_length_ratio': 0.25,
│   'dist_penalty_weight': 1.0,
│   'batch_size': 4,
│   'open_in_gui': False,
│   'peak_threshold': 0.2,
│   'max_instances': None,
│   'tracking.tracker': 'simplemaxtracks',
│   'tracking.target_instance_count': None,
│   'tracking.pre_cull_to_target': None,
│   'tracking.pre_cull_iou_threshold': None,
│   'tracking.post_connect_single_breaks': 1,
│   'tracking.clean_instance_count': None,
│   'tracking.clean_iou_threshold': None,
│   'tracking.similarity': None,
│   'tracking.match': None,
│   'tracking.robust': None,
│   'tracking.track_window': None,
│   'tracking.min_new_track_points': None,
│   'tracking.min_match_points': None,
│   'tracking.img_scale': None,
│   'tracking.of_window_size': None,
│   'tracking.of_max_levels': None,
│   'tracking.save_shifted_instances': None,
│   'tracking.kf_node_indices': None,
│   'tracking.kf_init_frame_count': None
}

INFO:sleap.nn.inference:Auto-selected GPU 0 with 40373 MiB of free memory.
Versions:
SLEAP: 1.3.1
TensorFlow: 2.7.0
Numpy: 1.19.5
Python: 3.7.12
OS: Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-redhat-8.7-Ootpa

System:
GPUs: 1/2 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
  Device: /physical_device:GPU:1
         Available: False
        Initalized: False
     Memory growth: None

Video: /scratch/zt1/project/juntti-lab/shared/sleap/videos/08-07-2023_piz3_T6.mp4
Traceback (most recent call last):
  File "/home/mwestbr2/mambaforge/envs/sleap/bin/sleap-track", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.1', 'console_scripts', 'sleap-track')())
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5400, in main
    tracker = _make_tracker_from_cli(args)
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/inference.py", line 5334, in _make_tracker_from_cli
    tracker = Tracker.make_tracker_by_name(**policy_args["tracking"])
  File "/home/mwestbr2/mambaforge/envs/sleap/lib/python3.7/site-packages/sleap/nn/tracking.py", line 634, in make_tracker_by_name
    raise ValueError(f"{tracker} is not a valid tracker.")
ValueError: simplemaxtracks is not a valid tracker.
```

## How to reproduce

Attempt running the slurm script with simplemaxtracks chosen as parameter.

**Comment by roomrys** [comment]
Hi @mollywestbrook,

The `simplemaxtracks` was only added fairly recently in v1.3.3.

Thanks,
Liezl

**Comment by mollywestbrook** [comment]
Simple fix! Updated sleap to v.1.3.3 and no error thrown for invalid parameters. Thanks!
