### ISSUE TITLE
shape mismatch error using resnet

### ISSUE THREAD

**Issue by milesOIST** [talmolab/sleap#1770]
# Bug description
When running resnet with certain settings, get a mismatch of sizes error

## Your personal set up

- OS:

- Version(s):

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)
> 

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
> INFO:sleap.nn.training:
> INFO:sleap.nn.training:Auto-selected GPU 0 with 16183 MiB of free memory.
> INFO:sleap.nn.training:Using GPU 0 for acceleration.
> INFO:sleap.nn.training:Disabled GPU memory pre-allocation.
> INFO:sleap.nn.training:System:
> GPUs: 1/1 available
>   Device: /physical_device:GPU:0
>          Available: True
>         Initalized: False
>      Memory growth: True
> INFO:sleap.nn.training:
> INFO:sleap.nn.training:Initializing trainer...
> INFO:sleap.nn.training:Loading training labels from: Z:/KuhnU/Miles-Kuhn/SLEAP/NewModel2.slp
> INFO:sleap.nn.training:Creating training and validation splits from validation fraction: 0.1
> INFO:sleap.nn.training:  Splits: Training = 1416 / Validation = 157.
> INFO:sleap.nn.training:Setting up for training...
> INFO:sleap.nn.training:Setting up pipeline builders...
> INFO:sleap.nn.training:Setting up model...
> INFO:sleap.nn.training:Building test pipeline...
> 2024-05-14 20:16:14.066762: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2024-05-14 20:16:16.252042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13599 MB memory:  -> device: 0, name: NVIDIA RTX A4000, pci bus id: 0000:01:00.0, compute capability: 8.6
> 2024-05-14 20:16:19.767318: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
> INFO:sleap.nn.training:Loaded test example. [273.244s]
> INFO:sleap.nn.training:  Input shape: (432, 576, 1)
> INFO:sleap.nn.training:Created Keras model.
> INFO:sleap.nn.training:  Backbone: ResNet152(upsampling_stack=UpsamplingStack(output_stride=2, upsampling_stride=2, transposed_conv=False, transposed_conv_filters=64, transposed_conv_filters_rate=1.0, transposed_conv_kernel_size=4, transposed_conv_batchnorm=True, make_skip_connection=False, skip_add=False, refine_convs=2, refine_convs_filters=64, refine_convs_filters_rate=1.0, refine_convs_batchnorm=True), features_output_stride=32, pretrained=True, frozen=True, skip_connections=False, model_name='resnet152', stack_configs=[{'filters': 64, 'blocks': 3, 'stride1': 1, 'name': 'conv2', 'dilation_rate': 1}, {'filters': 128, 'blocks': 8, 'stride1': 2, 'name': 'conv3', 'dilation_rate': 1}, {'filters': 256, 'blocks': 36, 'stride1': 2, 'name': 'conv4', 'dilation_rate': 1}, {'filters': 512, 'blocks': 3, 'stride1': 2, 'name': 'conv5', 'dilation_rate': 1}])
> INFO:sleap.nn.training:  Max stride: 32
> INFO:sleap.nn.training:  Parameters: 59,811,915
> INFO:sleap.nn.training:  Heads:
> INFO:sleap.nn.training:    [0] = SingleInstanceConfmapsHead(part_names=['eyelid top', 'eyelid bottom', 'nose right', 'nose left', 'spout', 'mouth lip top', 'mouth corner', 'paw right', 'paw left', 'tongue', 'mouth lip bottom'], sigma=2.5, output_stride=2, loss_weight=1.0)
> INFO:sleap.nn.training:  Outputs:
> INFO:sleap.nn.training:    [0] = KerasTensor(type_spec=TensorSpec(shape=(None, 224, 288, 11), dtype=tf.float32, name=None), name='SingleInstanceConfmapsHead/BiasAdd:0', description="created by layer 'SingleInstanceConfmapsHead'")
> INFO:sleap.nn.training:Training from scratch
> INFO:sleap.nn.training:Setting up data pipelines...
> INFO:sleap.nn.training:Training set: n = 1416
> INFO:sleap.nn.training:Validation set: n = 157
> INFO:sleap.nn.training:Setting up optimization...
> INFO:sleap.nn.training:  OHKM enabled: HardKeypointMiningConfig(online_mining=True, hard_to_easy_ratio=2.0, min_hard_keypoints=2, max_hard_keypoints=None, loss_scale=5.0)
> INFO:sleap.nn.training:  Learning rate schedule: LearningRateScheduleConfig(reduce_on_plateau=True, reduction_factor=0.5, plateau_min_delta=1e-06, plateau_patience=5, plateau_cooldown=3, min_learning_rate=1e-08)
> INFO:sleap.nn.training:  Early stopping: EarlyStoppingConfig(stop_training_on_plateau=True, plateau_min_delta=1e-08, plateau_patience=15)
> INFO:sleap.nn.training:Setting up outputs...
> INFO:sleap.nn.callbacks:Training controller subscribed to: tcp://127.0.0.1:9000 (topic: )
> INFO:sleap.nn.training:  ZMQ controller subcribed to: tcp://127.0.0.1:9000
> INFO:sleap.nn.callbacks:Progress reporter publishing on: tcp://127.0.0.1:9001 for: not_set
> INFO:sleap.nn.training:  ZMQ progress reporter publish on: tcp://127.0.0.1:9001
> INFO:sleap.nn.training:Created run path: Z:/KuhnU/Miles-Kuhn/SLEAP\models\240514_201219.single_instance.n=1573
> INFO:sleap.nn.training:Setting up visualization...
> C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py:1177: UserWarning: Model input of shape (None, 432, 576, 1) does not divide evenly with output of shape (None, 224, 288, 11).
>   f"Model input of shape {model.inputs[input_ind].shape} does not divide "
> INFO:sleap.nn.training:Finished trainer set up. [314.1s]
> INFO:sleap.nn.training:Creating tf.data.Datasets for training data generation...
> INFO:sleap.nn.training:Finished creating training datasets. [5796.8s]
> INFO:sleap.nn.training:Starting training loop...
> Epoch 1/500
> Traceback (most recent call last):
>   File "C:\Users\ONS\anaconda3\envs\sleap\Scripts\sleap-train-script.py", line 33, in <module>
>     sys.exit(load_entry_point('sleap==1.3.0', 'console_scripts', 'sleap-train')())
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 2014, in main
>     trainer.train()
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 943, in train
>     verbose=2,
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\keras\engine\training.py", line 1184, in fit
>     tmp_logs = self.train_function(iterator)
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
>     result = self._call(*args, **kwds)
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
>     self._initialize(args, kwds, add_initializers_to=initializers)
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\eager\def_function.py", line 760, in _initialize
>     *args, **kwds))
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\eager\function.py", line 3066, in _get_concrete_function_internal_garbage_collected
>     graph_function, _ = self._maybe_define_function(args, kwargs)
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\eager\function.py", line 3463, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\eager\function.py", line 3308, in _create_graph_function
>     capture_by_value=self._capture_by_value),
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1007, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\eager\def_function.py", line 668, in wrapped_fn
>     out = weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\func_graph.py", line 994, in wrapper
>     raise e.ag_error_metadata.to_exception(e)
> ValueError: in user code:
> 
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\keras\engine\training.py:853 train_function  *
>         return step_function(self, iterator)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\sleap\nn\training.py:303 loss_fn  *
>         loss += loss_fn(y_gt, y_pr)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\keras\losses.py:141 __call__  **
>         losses = call_fn(y_true, y_pred)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\keras\losses.py:245 call  **
>         return ag_fn(y_true, y_pred, **self._fn_kwargs)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
>         return target(*args, **kwargs)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\keras\losses.py:1204 mean_squared_error
>         return backend.mean(tf.math.squared_difference(y_pred, y_true), axis=-1)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\gen_math_ops.py:10514 squared_difference
>         "SquaredDifference", x=x, y=y, name=name)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\op_def_library.py:750 _apply_op_helper
>         attrs=attr_protos, op_def=op_def)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\func_graph.py:601 _create_op_internal
>         compute_device)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\ops.py:3569 _create_op_internal
>         op_def=op_def)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\ops.py:2042 __init__
>         control_input_ops, op_def)
>     C:\Users\ONS\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\ops.py:1883 _create_c_op
>         raise ValueError(str(e))
> 
>     ValueError: Dimensions must be equal, but are 224 and 216 for '{{node loss_fn/mean_squared_error/SquaredDifference}} = SquaredDifference[T=DT_FLOAT](model/SingleInstanceConfmapsHead/BiasAdd, IteratorGetNext:1)' with input shapes: [15,224,288,11], [15,216,288,?].
> 
> INFO:sleap.nn.callbacks:Closing the reporter controller/context.
> INFO:sleap.nn.callbacks:Closing the training controller socket/context.
> Run Path: Z:/KuhnU/Miles-Kuhn/SLEAP\models\240514_201219.single_instance.n=1573

</details>

**Comment by eberrigan** [comment]
Hi @milesOIST,

Would you mind uploading a sleap package with your training data [here](https://docs.google.com/forms/d/e/1FAIpQLSfWBwcuZH8lxGyFabMAODLjSUE4YrSCYbrrnYvXCpgBqZpcJA/viewform) so I can try replicating your issue? 

Also, you mentioned certain settings. Which settings did you notice this error happening with?

Thanks!

Elizabeth

**Comment by eberrigan** [comment]
This could be related to #1768.

**Comment by talmo** [comment]
Closing — the specific bug here was a `pad_to_stride` default in the TF backend that didn't account for backbone stride. With ResNet152 (`max_stride=32`) and a 432×576 input, the model output landed at 224×288 while the ground truth was at 216×288 — hence the `Dimensions must be equal, but are 224 and 216` mismatch.

The fix in legacy SLEAP (v1.4.x line) was [`0df91f08`](https://github.com/talmolab/sleap/commit/0df91f08), which auto-bumps `pad_to_stride` to at least the backbone's `maximum_stride` for every trainer type.

Note that SLEAP 1.5+ migrated training to PyTorch via [`sleap-nn`](https://github.com/talmolab/sleap-nn), which always applies pad-to-stride in the data + inference pipelines — so this class of mismatch can't occur there. ResNet itself isn't yet reimplemented in sleap-nn though; tracked at [talmolab/sleap-nn#568](https://github.com/talmolab/sleap-nn/issues/568) for users who want to keep using ResNet backbones.
