### ISSUE TITLE
Error running inference

### ISSUE THREAD

**Issue by GxHam** [talmolab/sleap#1856]
# Bug description

Unable to run inference or tracking after training reliable model.

## Expected behaviour

I followed the tutorial and iteratively trained a reliable model using "Predict" -> "Run Training" -> "Multi-animal-top-down" to recognize two interacting animals, and am trying to use "Run inference" to track animals on a section of my video (999 frames, obtained from suggested frames". 

## Actual behaviour
When using the "Predict" -> "Run Inference" window, I consistently run into the following error no matter what settings I use.

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\sleap_v1.4.1a1\lib\site-packages\sleap\gui\learning\dialog.py", line 731, in run
    items_for_inference=items_for_inference,
  File "C:\ProgramData\anaconda3\envs\sleap_v1.4.1a1\lib\site-packages\sleap\gui\learning\runners.py", line 559, in run_learning_pipeline
    save_viz=save_viz,
  File "C:\ProgramData\anaconda3\envs\sleap_v1.4.1a1\lib\site-packages\sleap\gui\learning\runners.py", line 618, in run_gui_training
    inference_params["controller_port"] = win.zmq_ports["controller_port"]
TypeError: 'NoneType' object is not subscriptable

I can label frames using "Run Training" though, only "Run Inference fails".

## Your personal set up
SLEAP v1.4.1a1

**Comment by GxHam** [comment]
Realized the issue was fixed in v1.4.1a2.
