### ISSUE TITLE
Typo (?) in inference code in tracker.py (curr_track vs. curr_track_id)

### ISSUE THREAD

**Issue by YiLin-Zhou** [talmolab/sleap#1997]
## Bug description

Running `dreem-train` on sleap data throws a `ConfigAttributeError: Key 'model' is not in struct`.

## Fix

Changing line 197  `curr_track += 1`  in dreem/inference/tracker.py to the following:
```
curr_track_id += 1
```
fixed this issue. Given the surrounding lines all reference ` curr_track_id` , I think it was just a typo.

## Logs

```
Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\Users\ylzhou\dreem\dreem\training\train.py", line 55, in run
    model = train_cfg.get_model()
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ylzhou\dreem\dreem\io\config.py", line 94, in get_model
    model_params = self.cfg.model
                   ^^^^^^^^^^^^^^
omegaconf.errors.ConfigAttributeError: Key 'model' is not in struct
    full_key: model
    object_type=dict
```

**Comment by YiLin-Zhou** [comment]
Meant to put this in the DREEM github repo. Sorry!
