### ISSUE TITLE
Attempted merge on macOS causes "ValueError: Labels.skeleton can only be used when there is only a single skeleton saved in the labels. Use Labels.skeletons instead."

### ISSUE THREAD

**Issue by christinaveed** [talmolab/sleap#2005]
# Bug description

I created a new .slp file and tried to merge an old file into it using File --> Merge into project. The merge failed and I got an error message instead.

## Expected behaviour

I expected data from the old file to merge into the new file.

## Actual behaviour

The merge fails and I get an error message in the terminal.

## Your personal set up

- OS:

macOS 15.0.1
- Version(s):

SLEAP v1.4.1a2, python 3.9.19
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [x] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

2024-10-23 15:40:00.492 python[13934:745483] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-23 15:40:00.492 python[13934:745483] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
2024-10-23 15:40:02.404 python[13934:745483] The class 'NSOpenPanel' overrides the method identifier.  This method is implemented by class 'NSWindow'
Traceback (most recent call last):
  File "/Users/christinahviid/sleap/sleap/gui/commands.py", line 608, in mergeProject
    self.execute(MergeProject, filenames=filenames)
  File "/Users/christinahviid/sleap/sleap/gui/commands.py", line 241, in execute
    command().execute(context=self, params=kwargs)
  File "/Users/christinahviid/sleap/sleap/gui/commands.py", line 133, in execute
    self.ask_and_do(context, params)
  File "/Users/christinahviid/sleap/sleap/gui/commands.py", line 2849, in ask_and_do
    MergeDialog(base_labels=context.labels, new_labels=new_labels).exec_()
  File "/Users/christinahviid/sleap/sleap/gui/dialogs/merge.py", line 51, in __init__
    if self.base_labels.skeleton.node_names != self.new_labels.skeleton.node_names:
  File "/Users/christinahviid/sleap/sleap/io/dataset.py", line 563, in skeleton
    raise ValueError(
ValueError: Labels.skeleton can only be used when there is only a single skeleton saved in the labels. Use Labels.skeletons instead.

```
# paste relevant logs here, if any
```

</details>

**Comment by eberrigan** [comment]
Hi @christinaveed, 

Are your skeletons matching (including node names)?

Best,

Elizabeth
