### ISSUE TITLE
Found multiple skeletons after running inference

### ISSUE THREAD

**Issue by Desvino** [talmolab/sleap#2025]
Hi! Thanks for your help!

# Bug description

We first encountered this bug when we tried to use relabelled instances to run training.

When performing a single animal project, it turned to
```
ValueError: Labels.skeleton can only be used when there is only a single skeleton saved in the labels. Use Labels.skeletons instead. 
```
But it could run when we restarted Sleap.

However, when performing a multiple animal top-down project, it turned to
```
Traceback (most recent call last):
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\Scripts\sleap-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.4', 'console_scripts', 'sleap-train')())
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 2014, in main
    trainer.train()
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 924, in train
    self.setup()
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 910, in setup
    self._setup_model()
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 727, in _setup_model
    base_example = next(iter(base_pipeline.make_dataset()))
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 800, in __next__
    return self._next_internal()
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 786, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2844, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\MiaoLab-Guest\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 2 is not in [0, 1)
         [[{{node GatherV2}}]] [Op:IteratorGetNext]
```
In this case, it couldn't run when we restarted Sleap.
I think it is a similar issue to #713 and #1090. 
When we tried methods you provided in #713 , we found that there were 3 skeletons in our project. These 3 skeletons were totally the same. After deleting the other skeletons, we could run training.
So I think multiple skeletons appeared as followed:

- Add videos into new project
- Run inference using previous model
- Edit instances
- Run training
- See error

We want to know how can we avoid this bug.Thank you very much!

## Your personal set up

- OS: Windows 10

- Version(s): Sleap v1.3.4

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  -  [Conda from package](https://sleap.ai/installation.html#conda-package)

**Comment by gitttt-1234** [comment]
Hi @Desvino !

Apologies for the delay! I tried the steps that you mentioned, but I'm not able to replicate this error. Could you please let me know if you added any skeletons to the project before running inference using previous model? 

Thanks,

Divya

**Comment by Desvino** [comment]
Hi @gitttt-1234 !
Thanks for your kindly reply!
I'm sure we didn't use the `Load Skeleton` option to the project. Recently we found that if we added 3 videos into new project, at last there would be 3 skeletons. While if we added 11 videos into new project, at last there would be 11 skeletons. I doubt if there were something wrong with our trained model.

Thanks,
Desvino

**Comment by gitttt-1234** [comment]
Hi @Desvino,

Thank you for getting back! I'm still not able to replicate the error at my side. Let's try to isolate where the duplicate skeletons are created. Could you please confirm if you were able to see multiple skeletons right after running inference with an existing model (in the `.slp` file generated after running inference)? It would be great if you could share your `training_config.json` for the existing ckpt and a couple of your videos on which you ran inference to debug better on our end. You can upload the files [here](https://docs.google.com/forms/d/e/1FAIpQLSfWBwcuZH8lxGyFabMAODLjSUE4YrSCYbrrnYvXCpgBqZpcJA/viewform).

Thanks,

Divya

**Comment by Desvino** [comment]
Hi @gitttt-1234 !

I have checked that I found multiple skeletons right after running inference with an existing mode, without any other steps. And I have uploaded the files you mentioned.
Thanks a lot!

Desvino

**Comment by gitttt-1234** [comment]
Hi @Desvino!

Thank you for sending the data, I was able to replicate the issue. Thanks @roomrys for your detailed analysis [here](https://github.com/talmolab/sleap/issues/1090#issuecomment-1412902769).
We're currently working on fixing this in #2075! I'll update once it's merged in and then you can install sleap from source using the below steps, which would resolve the issue:

- git clone https://github.com/talmolab/sleap && cd sleap
- conda env create -f environment.yml -n sleap_dev
Ref: [conda from source](https://sleap.ai/develop/installation.html#installation-methods)

Thanks,

Divya

**Comment by Desvino** [comment]
Hi @gitttt-1234 !
Thank you for your quick response and for looking into the issue. I really appreciate your efforts to fix the bug and will look forward to the update once it's resolved!

Best regards,
Desvino

**Comment by rachelmcassidy** [comment]
Hello,

I noticed some issues with duplicate skeletons in my project that were preventing me from merging labels into a previous one. I updated dataset.py to the latest version in #2075, and it did clean up the skeletons.

However, I noticed that whenever the single skeleton is assigned to the instances in my labels in _update_from_labels, instance.points is overwritten with an empty array.

This is an example instance before and after the merge:
![image](https://github.com/user-attachments/assets/14c63409-febd-4488-9002-651f30bb443d)

![image](https://github.com/user-attachments/assets/0462462a-7017-470a-a0f7-2f44e1ce2062)

And if I print the instance before and after the skeleton assignment:

```
for instance in lf.instances:
    #print(instance)
    for skeleton in skeletons:
        #print(skeleton)
        # check if the new skeleton is already in labels.skeletons
        if not skeleton.matches(instance.skeleton):
            print('not a match')
            skeletons.append(instance.skeleton)
        else:
            # assign the existing skeleton if the instance has duplicate skeleton
            print(instance)
            
            instance.skeleton = skeleton
            
            print(instance)
```
I get output like this:

```
Instance(video=Video(filename=filepath/vid_2025-03-26T14_13_16.avi, shape=(5546, 1544, 2064, 1), backend=MediaVideo), frame_idx=5545, points=[nose1: (416.6, 808.6), earL1: (437.6, 764.7), earR1: (401.2, 764.7), tailstart1: (422.5, 634.9)], track=None)

Instance(video=Video(filename=filepath/vid_2025-03-26T14_13_16.avi, shape=(5546, 1544, 2064, 1), backend=MediaVideo), frame_idx=5545, points=[], track=None)

```
If I comment out instance.skeleton = skeleton, the points array is still there but the file fails to save.

Thanks for all your work on this - I'll be sure to check back when this bug is resolved! I have seen the same multiple skeletons error as this one (https://github.com/talmolab/sleap/issues/2142#issuecomment-2734643866) with this project as well, and before I needed to merge labels, it was usually solved with closing and reopening the gui. I'm not sure if this would make a difference, but the labels I'm working with are all corrected predictions from an existing model. The number of skeletons might correspond to the number of inferences I ran or the number of videos, but I'm not certain.

Best regards,
Rachel

**Comment by talmo** [comment]
Hi @Desvino and @rachelmcassidy — thanks for the reports and the data.

This was fixed by [PR #2282](https://github.com/talmolab/sleap/pull/2282) ("Integrate sleap io `Skeleton` to SLEAP GUI", merged 2025-08-29, in v1.5+). The legacy inference→merge path used to dedup skeletons by Python-object identity (so each fresh `Skeleton` from a new inference run accumulated — N runs → N skeletons), and #2282 replaced that with the sleap-io merge stack at `sleap/gui/learning/runners.py:767-769`:

```python
self.labels.merge(new_labels, frame="replace_predictions")  # or "keep_both"
```

`sleap-io.Labels.merge()` defaults to structural skeleton matching (see [the merging guide](https://sleap.ai/api/sleap_io.model.labels.html#sleap_io.model.labels.Labels.merge)), so content-equal skeletons from inference are canonicalized to the project's skeleton automatically. PR #2075's blocker (points were keyed by `Node` identity and got blanked on skeleton swap) is gone in the new data model — `Instance.points` is now a positional array, so reassignment is safe.

**If you're still on 1.3 / 1.4** with affected `.slp` files: @roomrys's [dedup script](https://github.com/talmolab/sleap/issues/1090#issuecomment-1381176317) on #1090 cleans up the redundant skeletons (caveat: it doesn't remap `Instance.points`, so only safe if the canonical skeleton has identical node names *in the same order* — which is the normal case for inference-emitted duplicates). After cleanup, upgrade to 1.5+ and the bug stays fixed.

Closing as completed. Thanks again for catching this and pushing on it.
