### ISSUE TITLE
Error when installing: "The 'wheel>=0.26' distribution was not found and is required by tensorflow"

### ISSUE THREAD

**Issue by rojasgabriel** [talmolab/sleap#590]
Hello! I've been trying to reinstall sleap on my computer and after reinstalling anaconda and sleap, I keep getting this error when trying to run `sleap-label`:

`(base) C:\Users\honglabuser>conda activate sleap

(sleap) C:\Users\honglabuser>sleap-label
Traceback (most recent call last):
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.19.5 (c:\users\honglabuser\.conda\envs\sleap\lib\site-packages), Requirement.parse('numpy<1.19.0,>=1.18.1'), {'sleap'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\honglabuser\.conda\envs\sleap\Scripts\sleap-label-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.1.5', 'console_scripts', 'sleap-label')())
  File "C:\Users\honglabuser\.conda\envs\sleap\Scripts\sleap-label-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\importlib_metadata\__init__.py", line 93, in load
    module = import_module(match.group('module'))
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\sleap\__init__.py", line 9, in <module>
    from sleap.io.dataset import Labels, load_file
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\sleap\io\dataset.py", line 61, in <module>
    from sklearn.model_selection import train_test_split
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\sklearn\base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\sklearn\utils\__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\sklearn\utils\class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\sklearn\utils\validation.py", line 26, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\sklearn\utils\fixes.py", line 28, in <module>
    from pkg_resources import parse_version  # type: ignore
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 3242, in <module>
    @_call_aside
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Users\honglabuser\.conda\envs\sleap\lib\site-packages\pkg_resources\__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel>=0.26' distribution was not found and is required by tensorflow`

**Comment by rojasgabriel** [comment]
Wow, that actually fixed it! It seems that I had numpy 1.19.5 installed and that was giving me the error.
