### ISSUE TITLE
SLEAP is not working with Relative Addresses

### ISSUE THREAD

**Issue by aarahvar2** [talmolab/sleap#895]
# Bug description

## Expected behaviour
When you transfer a project from one computer to another, Sleap should handle all addresses in the project according to the relative address (not absolute address).

## Actual behaviour
When I transfer a project from one computer to another, Sleap looks for Absolute address for the loaded video. Even if I give it the new address in the new computer, it seems that in some places in the code, the absolute address remain. For example, if in the above scenario you want to train the network in the new computer, you will get an error complaining about the primary absolute address in the first computer.

## Your personal set up

- OS: Windows 

- Version(s):10

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [x ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [M1 Macs](https://sleap.ai/installation.html#m1-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Project\python\sleap_env\kp\Scripts\sleap-train.exe\__main__.py", line 7, in <module>
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\nn\training.py", line 1947, in main
    trainer.train()
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\nn\training.py", line 906, in train
    self.setup()
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\nn\training.py", line 892, in setup
    self._setup_model()
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\nn\training.py", line 725, in _setup_model
    base_example = next(iter(base_pipeline.make_dataset()))
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\nn\data\pipelines.py", line 282, in make_dataset
    ds = self.providers[0].make_dataset()
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\nn\data\providers.py", line 187, in make_dataset
    first_image = tf.convert_to_tensor(self.labels[0].image)
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\instance.py", line 1757, in image
    return self.video.get_frame(self.frame_idx)
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\io\video.py", line 1088, in get_frame
    return self.backend.get_frame(idx)
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\io\video.py", line 486, in get_frame
    if self.__reader.get(cv2.CAP_PROP_POS_FRAMES) != idx:
  File "F:\Project\python\sleap_env\kp\lib\site-packages\sleap\io\video.py", line 381, in __reader
    f"Could not find filename video filename named {self.filename}"
FileNotFoundError: Could not find filename video filename named C:/ABSOLUTE ADDRESS IN THE FIRST COMPUTER/IMG_6547.mp4

```

</details>

## How to reproduce

Transfer a project from one computer to another and try to train in the new computer.

**Comment by roomrys** [comment]
Hi @aarahvar2,

Thanks for reporting!

Once the project is saved, SLEAP will update the paths in the project. SLEAP should force users to save after finding missing videos - which we are working on implementing. The workaround is to save the project after you find the missing videos.  

Closing this issue and following up in #848.

Thanks,
Liezl
