### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError, dimension size mismatch in dimension (during prediction)

### ISSUE THREAD

**Issue by maggie-jiayizhang** [talmolab/sleap#976]
Hi SLEAP team,

I keep encountering a dimension mismatch issue during prediction (after training is run). I am not sure which dimensions mismatching, so I would really appreciate if you could take a look/give some suggestions. I pasted the software versions and error message below. 

Thank you!!

Software versions:
SLEAP: 1.1.4
TensorFlow: 2.3.1
Numpy: 1.18.5
Python: 3.6.13
OS: Windows-10-10.0.19041-SP0

````
Predicting... ----------------------------------------   0% ETA: -:--:-- ? Polling: [some folder]
Predicting... --------- ------------------------------  24% ETA: 0:00:59 9.0 FPS
Traceback (most recent call last):
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1296, in truediv
    return _truediv_python3(x, y, name)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1221, in _truediv_python3
    x = ops.convert_to_tensor(x, name="x")
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\framework\ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\framework\constant_op.py", line 338, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\framework\constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\framework\constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\framework\constant_op.py", line 300, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\framework\constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: TypeError: object of type 'RaggedTensor' has no len()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~\.conda\envs\sleap\Scripts\sleap-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.1.4', 'console_scripts', 'sleap-train')())
  File "~\.conda\envs\sleap\lib\site-packages\sleap\nn\training.py", line 1617, in main
    trainer.train()
  File "~\.conda\envs\sleap\lib\site-packages\sleap\nn\training.py", line 904, in train
    self.evaluate()
  File "~\.conda\envs\sleap\lib\site-packages\sleap\nn\training.py", line 917, in evaluate
    split_name="train",
  File "~\.conda\envs\sleap\lib\site-packages\sleap\nn\evals.py", line 699, in evaluate_model
    labels_pr = predictor.predict(labels_reader, make_labels=True)
  File "~\.conda\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 390, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "~\.conda\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 2010, in _make_labeled_frames_from_generator
    for ex in generator:
  File "~\.conda\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 300, in _predict_generator
    ex = process_batch(ex)
  File "~\.conda\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 279, in process_batch
    np.expand_dims(ex["scale"], axis=1), axis=1
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\util\dispatch.py", line 205, in wrapper
    result = dispatch(wrapper, args, kwargs)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\util\dispatch.py", line 118, in dispatch
    result = dispatcher.handle(args, kwargs)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\ops\ragged\ragged_dispatch.py", line 219, in handle
    ragged_tensor_shape.RaggedTensorDynamicShape.from_tensor(y))
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor_shape.py", line 470, in broadcast_dynamic_shape
    shape_x = shape_x.broadcast_dimension(axis, shape_y.dimension_size(axis))
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor_shape.py", line 351, in broadcast_dimension
    condition, data=broadcast_err, summarize=10)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
  File "~\.conda\envs\sleap\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 158, in Assert
    (condition, "\n".join(data_str)))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'Unable to broadcast: dimension size mismatch in dimension'
0
b'lengths='
4
b'dim_size='
3
INFO:sleap.nn.callbacks:Closing the reporter controller/context.
INFO:sleap.nn.callbacks:Closing the training controller socket/context.
```

**Comment by roomrys** [comment]
Hi @maggie-jiayizhang,

Do you mind upgrading to the newest version of [SLEAP v1.2.8](https://sleap.ai/installation.html#installation-methods)?

Let us know if that fixes things.

Thanks,
Liezl

**Comment by maggie-jiayizhang** [comment]
Hi Liezl,

Thanks for the timely suggestion! I will try and let you know! (I also saw a thread about a similar/same issue: [link](https://github.com/talmolab/sleap/issues/635) I might also try changing batch size).

Best,
Jiayi

**Comment by maggie-jiayizhang** [comment]
I don't see this issue anymore after updating sleap. Thanks!
